//------------------------------------------------------------------------------
// *** DO NOT INCLUDE DIRECTLY ***
//
// These macros generate code and populate several tables related to opcodes automatically.
//------------------------------------------------------------------------------

Z80_OPCODE(00, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(01, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(02, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(03, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(04, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(05, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(06, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(07, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(08, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(09, true, "ADD", "IX", "BC", TIMING_F4I4I3, { ADD16_reg_reg(&m_registers.IX, m_registers.BC); })
Z80_OPCODE(0A, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(0B, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(0C, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(0D, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(0E, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(0F, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(10, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(11, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(12, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(13, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(14, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(15, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(16, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(17, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(18, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(19, true, "ADD", "IX", "DE", TIMING_F4I4I3, { ADD16_reg_reg(&m_registers.IX, m_registers.DE); })
Z80_OPCODE(1A, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(1B, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(1C, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(1D, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(1E, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(1F, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(20, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(21, true, "LD", "IX", "%nn", TIMING_F4M3M3, { LD16_reg_nn(&m_registers.IX); })
Z80_OPCODE(22, true, "LD", "(%nn)", "IX", TIMING_F4M3M3M3M3, { LD16_addrnn_reg(m_registers.IX); })
Z80_OPCODE(23, true, "INC", "IX", "", TIMING_F6, { INC16_reg(&m_registers.IX); })
Z80_OPCODE(24, true, "INC", "IXH", "", TIMING_F4, { INC8_reg(&m_registers.IXH()); })
Z80_OPCODE(25, true, "DEC", "IXH", "", TIMING_F4, { DEC8_reg(&m_registers.IXH()); })
Z80_OPCODE(26, true, "LD", "IXH", "%n", TIMING_F4M3, { LD8_reg_n(&m_registers.IXH()); })
Z80_OPCODE(27, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(28, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(29, true, "ADD", "IX", "IX", TIMING_F4I4I3, { ADD16_reg_reg(&m_registers.IX, m_registers.IX); })
Z80_OPCODE(2A, true, "LD", "IX", "(%nn)", TIMING_F4M3M3M3M3, { LD16_reg_addrnn(&m_registers.IX); })
Z80_OPCODE(2B, true, "DEC", "IX", "", TIMING_F6, { DEC16_reg(&m_registers.IX); })
Z80_OPCODE(2C, true, "INC", "IXL", "", TIMING_F4, { INC8_reg(&m_registers.IXL()); })
Z80_OPCODE(2D, true, "DEC", "IXL", "", TIMING_F4, { DEC8_reg(&m_registers.IXL()); })
Z80_OPCODE(2E, true, "LD", "IXL", "%n", TIMING_F4M3, { LD8_reg_n(&m_registers.IXL()); })
Z80_OPCODE(2F, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(30, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(31, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(32, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(33, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(34, true, "INC", "(IX + %n)", "", TIMING_F4M3I5M4M3, { INC8_addrreg_offset(m_registers.IX); })
Z80_OPCODE(35, true, "DEC", "(IX + %n)", "", TIMING_F4M3I5M4M3, { DEC8_addrreg_offset(m_registers.IX); })
Z80_OPCODE(36, true, "LD", "(IX + %n)", "%n", TIMING_F4M3M3I5M3, { LD8_addrreg_offset_n(m_registers.IX); })
Z80_OPCODE(37, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(38, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(39, true, "ADD", "IX", "SP", TIMING_F4I4I3, { ADD16_reg_reg(&m_registers.IX, m_registers.SP); })
Z80_OPCODE(3A, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(3B, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(3C, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(3D, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(3E, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(3F, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(40, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(41, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(42, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(43, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(44, true, "LD", "B", "IXH", TIMING_F4, { LD8_reg_reg(&m_registers.B(), m_registers.IXH()); })
Z80_OPCODE(45, true, "LD", "B", "IXL", TIMING_F4, { LD8_reg_reg(&m_registers.B(), m_registers.IXL()); })
Z80_OPCODE(46, true, "LD", "B", "(IX + %n)", TIMING_F4M3I5M3, { LD8_reg_addrreg_offset(&m_registers.B(), m_registers.IX); })
Z80_OPCODE(47, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(48, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(49, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(4A, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(4B, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(4C, true, "LD", "C", "IXH", TIMING_F4, { LD8_reg_reg(&m_registers.C(), m_registers.IXH()); })
Z80_OPCODE(4D, true, "LD", "C", "IXL", TIMING_F4, { LD8_reg_reg(&m_registers.C(), m_registers.IXL()); })
Z80_OPCODE(4E, true, "LD", "C", "(IX + %n)", TIMING_F4M3I5M3, { LD8_reg_addrreg_offset(&m_registers.C(), m_registers.IX); })
Z80_OPCODE(4F, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(50, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(51, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(52, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(53, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(54, true, "LD", "D", "IXH", TIMING_F4, { LD8_reg_reg(&m_registers.D(), m_registers.IXH()); })
Z80_OPCODE(55, true, "LD", "D", "IXL", TIMING_F4, { LD8_reg_reg(&m_registers.D(), m_registers.IXL()); })
Z80_OPCODE(56, true, "LD", "D", "(IX + %n)", TIMING_F4M3I5M3, { LD8_reg_addrreg_offset(&m_registers.D(), m_registers.IX); })
Z80_OPCODE(57, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(58, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(59, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(5A, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(5B, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(5C, true, "LD", "E", "IXH", TIMING_F4, { LD8_reg_reg(&m_registers.E(), m_registers.IXH()); })
Z80_OPCODE(5D, true, "LD", "E", "IXL", TIMING_F4, { LD8_reg_reg(&m_registers.E(), m_registers.IXL()); })
Z80_OPCODE(5E, true, "LD", "E", "(IX + %n)", TIMING_F4M3I5M3, { LD8_reg_addrreg_offset(&m_registers.E(), m_registers.IX); })
Z80_OPCODE(5F, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(60, true, "LD", "IXH", "B", TIMING_F4, { LD8_reg_reg(&m_registers.IXH(), m_registers.B()); })
Z80_OPCODE(61, true, "LD", "IXH", "C", TIMING_F4, { LD8_reg_reg(&m_registers.IXH(), m_registers.C()); })
Z80_OPCODE(62, true, "LD", "IXH", "D", TIMING_F4, { LD8_reg_reg(&m_registers.IXH(), m_registers.D()); })
Z80_OPCODE(63, true, "LD", "IXH", "E", TIMING_F4, { LD8_reg_reg(&m_registers.IXH(), m_registers.E()); })
Z80_OPCODE(64, true, "LD", "IXH", "IXH", TIMING_F4, { LD8_reg_reg(&m_registers.IXH(), m_registers.IXH()); })
Z80_OPCODE(65, true, "LD", "IXH", "IXL", TIMING_F4, { LD8_reg_reg(&m_registers.IXH(), m_registers.IXL()); })
Z80_OPCODE(66, true, "LD", "H", "(IX + %n)", TIMING_F4M3I5M3, { LD8_reg_addrreg_offset(&m_registers.H(), m_registers.IX); })
Z80_OPCODE(67, true, "LD", "IXH", "A", TIMING_F4, { LD8_reg_reg(&m_registers.IXH(), m_registers.A()); })
Z80_OPCODE(68, true, "LD", "IXL", "B", TIMING_F4, { LD8_reg_reg(&m_registers.IXL(), m_registers.B()); })
Z80_OPCODE(69, true, "LD", "IXL", "C", TIMING_F4, { LD8_reg_reg(&m_registers.IXL(), m_registers.C()); })
Z80_OPCODE(6A, true, "LD", "IXL", "D", TIMING_F4, { LD8_reg_reg(&m_registers.IXL(), m_registers.D()); })
Z80_OPCODE(6B, true, "LD", "IXL", "E", TIMING_F4, { LD8_reg_reg(&m_registers.IXL(), m_registers.E()); })
Z80_OPCODE(6C, true, "LD", "IXL", "IXH", TIMING_F4, { LD8_reg_reg(&m_registers.IXL(), m_registers.IXH()); })
Z80_OPCODE(6D, true, "LD", "IXL", "IXL", TIMING_F4, { LD8_reg_reg(&m_registers.IXL(), m_registers.IXL()); })
Z80_OPCODE(6E, true, "LD", "L", "(IX + %n)", TIMING_F4M3I5M3, { LD8_reg_addrreg_offset(&m_registers.L(), m_registers.IX); })
Z80_OPCODE(6F, true, "LD", "IXL", "A", TIMING_F4, { LD8_reg_reg(&m_registers.IXL(), m_registers.A()); })
Z80_OPCODE(70, true, "LD", "(IX + %n)", "B", TIMING_F4M3I5M3, { LD8_addrreg_offset_valuereg(m_registers.IX, m_registers.B()); })
Z80_OPCODE(71, true, "LD", "(IX + %n)", "C", TIMING_F4M3I5M3, { LD8_addrreg_offset_valuereg(m_registers.IX, m_registers.C()); })
Z80_OPCODE(72, true, "LD", "(IX + %n)", "D", TIMING_F4M3I5M3, { LD8_addrreg_offset_valuereg(m_registers.IX, m_registers.D()); })
Z80_OPCODE(73, true, "LD", "(IX + %n)", "E", TIMING_F4M3I5M3, { LD8_addrreg_offset_valuereg(m_registers.IX, m_registers.E()); })
Z80_OPCODE(74, true, "LD", "(IX + %n)", "H", TIMING_F4M3I5M3, { LD8_addrreg_offset_valuereg(m_registers.IX, m_registers.H()); })
Z80_OPCODE(75, true, "LD", "(IX + %n)", "L", TIMING_F4M3I5M3, { LD8_addrreg_offset_valuereg(m_registers.IX, m_registers.L()); })
Z80_OPCODE(76, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(77, true, "LD", "(IX + %n)", "A", TIMING_F4M3I5M3, { LD8_addrreg_offset_valuereg(m_registers.IX, m_registers.A()); })
Z80_OPCODE(78, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(79, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(7A, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(7B, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(7C, true, "LD", "A", "IXH", TIMING_F4, { LD8_reg_reg(&m_registers.A(), m_registers.IXH()); })
Z80_OPCODE(7D, true, "LD", "A", "IXL", TIMING_F4, { LD8_reg_reg(&m_registers.A(), m_registers.IXL()); })
Z80_OPCODE(7E, true, "LD", "A", "(IX + %n)", TIMING_F4M3I5M3, { LD8_reg_addrreg_offset(&m_registers.A(), m_registers.IX); })
Z80_OPCODE(7F, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(80, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(81, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(82, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(83, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(84, true, "ADD", "A", "IXH", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.IXH(), 0); })
Z80_OPCODE(85, true, "ADD", "A", "IXL", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.IXL(), 0); })
Z80_OPCODE(86, true, "ADD", "A", "(IX + %n)", TIMING_F4M3I5M3, { ADD8_reg_addrreg_offset(&m_registers.A(), m_registers.IX, 0); })
Z80_OPCODE(87, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(88, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(89, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(8A, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(8B, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(8C, true, "ADC", "A", "IXH", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.IXH(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8D, true, "ADC", "A", "IXL", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.IXL(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8E, true, "ADC", "A", "(IX + %n)", TIMING_F4M3I5M3, { ADD8_reg_addrreg_offset(&m_registers.A(), m_registers.IX, m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8F, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(90, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(91, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(92, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(93, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(94, true, "SUB", "IXH", "", TIMING_F4, { SUB8_reg(m_registers.IXH(), 0); })
Z80_OPCODE(95, true, "SUB", "IXL", "", TIMING_F4, { SUB8_reg(m_registers.IXL(), 0); })
Z80_OPCODE(96, true, "SUB", "(IX + %n)", "", TIMING_F4M3I5M3, { SUB8_addrreg_offset(m_registers.IX, 0); })
Z80_OPCODE(97, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(98, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(99, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(9A, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(9B, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(9C, true, "SBC", "A", "IXH", TIMING_F4, { SUB8_reg(m_registers.IXH(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9D, true, "SBC", "A", "IXL", TIMING_F4, { SUB8_reg(m_registers.IXL(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9E, true, "SBC", "A", "(IX + %n)", TIMING_F4M3I5M3, { SUB8_addrreg_offset(m_registers.IX, m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9F, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(A0, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(A1, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(A2, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(A3, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(A4, true, "AND", "IXH", "", TIMING_F4, { AND_reg(m_registers.IXH()); })
Z80_OPCODE(A5, true, "AND", "IXL", "", TIMING_F4, { AND_reg(m_registers.IXL()); })
Z80_OPCODE(A6, true, "AND", "(IX + %n)", "", TIMING_F4M3I5M3, { AND_addrreg_offset(m_registers.IX); })
Z80_OPCODE(A7, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(A8, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(A9, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(AA, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(AB, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(AC, true, "XOR", "IXH", "", TIMING_F4, { XOR_reg(m_registers.IXH()); })
Z80_OPCODE(AD, true, "XOR", "IXL", "", TIMING_F4, { XOR_reg(m_registers.IXL()); })
Z80_OPCODE(AE, true, "XOR", "(IX + %n)", "", TIMING_F4M3I5M3, { XOR_addrreg_offset(m_registers.IX); })
Z80_OPCODE(AF, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(B0, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(B1, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(B2, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(B3, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(B4, true, "OR", "IXH", "", TIMING_F4, { OR_reg(m_registers.IXH()); })
Z80_OPCODE(B5, true, "OR", "IXL", "", TIMING_F4, { OR_reg(m_registers.IXL()); })
Z80_OPCODE(B6, true, "OR", "(IX + %n)", "", TIMING_F4M3I5M3, { OR_addrreg_offset(m_registers.IX); })
Z80_OPCODE(B7, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(B8, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(B9, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(BA, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(BB, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(BC, true, "CP", "IXH", "", TIMING_F4, { CP_reg(m_registers.IXH()); })
Z80_OPCODE(BD, true, "CP", "IXL", "", TIMING_F4, { CP_reg(m_registers.IXL()); })
Z80_OPCODE(BE, true, "CP", "(IX + %n)", "", TIMING_F4M3I5M3, { CP_addrreg_offset(m_registers.IX); })
Z80_OPCODE(BF, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(C0, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(C1, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(C2, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(C3, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(C4, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(C5, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(C6, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(C7, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(C8, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(C9, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(CA, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(CB, false, "<CB prefix>", "", "", TIMING_F4, { ProcessPrefixByte(0xCB); })
Z80_OPCODE(CC, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(CD, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(CE, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(CF, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(D0, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(D1, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(D2, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(D3, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(D4, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(D5, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(D6, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(D7, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(D8, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(D9, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(DA, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(DB, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(DC, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(DD, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(DE, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(DF, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(E0, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(E1, true, "POP", "IX", "", TIMING_F4M3M3, { Pop(&m_registers.IX); })
Z80_OPCODE(E2, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(E3, true, "EX", "(SP)", "IX", TIMING_F4M3M4M3M5, { EX_addrreg_reg(m_registers.SP, &m_registers.IX); })
Z80_OPCODE(E4, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(E5, true, "PUSH", "IX", "", TIMING_F5M3M3, { Push(m_registers.IX); })
Z80_OPCODE(E6, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(E7, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(E8, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(E9, true, "JP", "(IX)", "", TIMING_F4, { JP_reg(m_registers.IX); })
Z80_OPCODE(EA, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(EB, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(EC, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(ED, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(EE, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(EF, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(F0, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(F1, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(F2, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(F3, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(F4, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(F5, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(F6, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(F7, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(F8, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(F9, true, "LD", "SP", "IX", TIMING_F6, { LD16_reg_reg(&m_registers.SP, m_registers.IX); })
Z80_OPCODE(FA, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(FB, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(FC, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(FD, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(FE, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
Z80_OPCODE(FF, true, "<Invalid instruction>", "", "", TIMING_F4, { HandleInvalidInstruction(); })
