//------------------------------------------------------------------------------
// *** DO NOT INCLUDE DIRECTLY ***
//
// These macros generate code and populate several tables related to opcodes automatically.
//------------------------------------------------------------------------------

Z80_OPCODE(00, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(01, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(02, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(03, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(04, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(05, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(06, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(07, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(08, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(09, true, "ADD IY, BC", { ADD16_reg_reg(&m_registers.IY, m_registers.BC); })
Z80_OPCODE(0A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(0B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(0C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(0D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(0E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(0F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(10, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(11, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(12, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(13, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(14, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(15, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(16, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(17, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(18, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(19, true, "ADD IY, DE", { ADD16_reg_reg(&m_registers.IY, m_registers.DE); })
Z80_OPCODE(1A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(1B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(1C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(1D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(1E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(1F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(20, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(21, true, "LD IY, %nn", { LD16_reg_nn(&m_registers.IY); })
Z80_OPCODE(22, true, "LD (%nn), IY", { LD16_addrnn_reg(m_registers.IY); })
Z80_OPCODE(23, true, "INC IY", { INC16_reg(&m_registers.IY); })
Z80_OPCODE(24, true, "INC IYH", { INC8_reg(&m_registers.IYH()); })
Z80_OPCODE(25, true, "DEC IYH", { DEC8_reg(&m_registers.IYH()); })
Z80_OPCODE(26, true, "LD IYH, %n", { LD8_reg_n(&m_registers.IYH()); })
Z80_OPCODE(27, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(28, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(29, true, "ADD IY, IY", { ADD16_reg_reg(&m_registers.IY, m_registers.IY); })
Z80_OPCODE(2A, true, "LD IY, (%nn)", { LD16_reg_addrnn(&m_registers.IY); })
Z80_OPCODE(2B, true, "DEC IY", { DEC16_reg(&m_registers.IY); })
Z80_OPCODE(2C, true, "INC IYL", { INC8_reg(&m_registers.IYL()); })
Z80_OPCODE(2D, true, "DEC IYL", { DEC8_reg(&m_registers.IYL()); })
Z80_OPCODE(2E, true, "LD IYL, %n", { LD8_reg_n(&m_registers.IYL()); })
Z80_OPCODE(2F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(30, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(31, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(32, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(33, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(34, true, "INC (IY + %n)", { INC8_addrreg_offset(m_registers.IY); })
Z80_OPCODE(35, true, "DEC (IY + %n)", { DEC8_addrreg_offset(m_registers.IY); })
Z80_OPCODE(36, true, "LD (IY + %n), %n", { LD8_addrreg_offset_n(m_registers.IY); })
Z80_OPCODE(37, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(38, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(39, true, "ADD IY, SP", { ADD16_reg_reg(&m_registers.IY, m_registers.SP); })
Z80_OPCODE(3A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(3B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(3C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(3D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(3E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(3F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(40, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(41, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(42, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(43, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(44, true, "LD B, IYH", { LD8_reg_reg(&m_registers.B(), m_registers.IYH()); })
Z80_OPCODE(45, true, "LD B, IYL", { LD8_reg_reg(&m_registers.B(), m_registers.IYL()); })
Z80_OPCODE(46, true, "LD B, (IY + %n)", { LD8_reg_addrreg_offset(&m_registers.B(), m_registers.IY); })
Z80_OPCODE(47, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(48, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(49, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(4A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(4B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(4C, true, "LD C, IYH", { LD8_reg_reg(&m_registers.C(), m_registers.IYH()); })
Z80_OPCODE(4D, true, "LD C, IYL", { LD8_reg_reg(&m_registers.C(), m_registers.IYL()); })
Z80_OPCODE(4E, true, "LD C, (IY + %n)", { LD8_reg_addrreg_offset(&m_registers.C(), m_registers.IY); })
Z80_OPCODE(4F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(50, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(51, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(52, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(53, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(54, true, "LD D, IYH", { LD8_reg_reg(&m_registers.D(), m_registers.IYH()); })
Z80_OPCODE(55, true, "LD D, IYL", { LD8_reg_reg(&m_registers.D(), m_registers.IYL()); })
Z80_OPCODE(56, true, "LD D, (IY + %n)", { LD8_reg_addrreg_offset(&m_registers.D(), m_registers.IY); })
Z80_OPCODE(57, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(58, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(59, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(5A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(5B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(5C, true, "LD E, IYH", { LD8_reg_reg(&m_registers.E(), m_registers.IYH()); })
Z80_OPCODE(5D, true, "LD E, IYL", { LD8_reg_reg(&m_registers.E(), m_registers.IYL()); })
Z80_OPCODE(5E, true, "LD E, (IY + %n)", { LD8_reg_addrreg_offset(&m_registers.E(), m_registers.IY); })
Z80_OPCODE(5F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(60, true, "LD IYH, B", { LD8_reg_reg(&m_registers.IYH(), m_registers.B()); })
Z80_OPCODE(61, true, "LD IYH, C", { LD8_reg_reg(&m_registers.IYH(), m_registers.C()); })
Z80_OPCODE(62, true, "LD IYH, D", { LD8_reg_reg(&m_registers.IYH(), m_registers.D()); })
Z80_OPCODE(63, true, "LD IYH, E", { LD8_reg_reg(&m_registers.IYH(), m_registers.E()); })
Z80_OPCODE(64, true, "LD IYH, IYH", { LD8_reg_reg(&m_registers.IYH(), m_registers.IYH()); })
Z80_OPCODE(65, true, "LD IYH, IYL", { LD8_reg_reg(&m_registers.IYH(), m_registers.IYL()); })
Z80_OPCODE(66, true, "LD H, (IY + %n)", { LD8_reg_addrreg_offset(&m_registers.H(), m_registers.IY); })
Z80_OPCODE(67, true, "LD IYH, A", { LD8_reg_reg(&m_registers.IYH(), m_registers.A()); })
Z80_OPCODE(68, true, "LD IYL, B", { LD8_reg_reg(&m_registers.IYL(), m_registers.B()); })
Z80_OPCODE(69, true, "LD IYL, C", { LD8_reg_reg(&m_registers.IYL(), m_registers.C()); })
Z80_OPCODE(6A, true, "LD IYL, D", { LD8_reg_reg(&m_registers.IYL(), m_registers.D()); })
Z80_OPCODE(6B, true, "LD IYL, E", { LD8_reg_reg(&m_registers.IYL(), m_registers.E()); })
Z80_OPCODE(6C, true, "LD IYL, IYH", { LD8_reg_reg(&m_registers.IYL(), m_registers.IYH()); })
Z80_OPCODE(6D, true, "LD IYL, IYL", { LD8_reg_reg(&m_registers.IYL(), m_registers.IYL()); })
Z80_OPCODE(6E, true, "LD L, (IY + %n)", { LD8_reg_addrreg_offset(&m_registers.L(), m_registers.IY); })
Z80_OPCODE(6F, true, "LD IYL, A", { LD8_reg_reg(&m_registers.IYL(), m_registers.A()); })
Z80_OPCODE(70, true, "LD (IY + %n), B", { LD8_addrreg_offset_valuereg(m_registers.IY, m_registers.B()); })
Z80_OPCODE(71, true, "LD (IY + %n), C", { LD8_addrreg_offset_valuereg(m_registers.IY, m_registers.C()); })
Z80_OPCODE(72, true, "LD (IY + %n), D", { LD8_addrreg_offset_valuereg(m_registers.IY, m_registers.D()); })
Z80_OPCODE(73, true, "LD (IY + %n), E", { LD8_addrreg_offset_valuereg(m_registers.IY, m_registers.E()); })
Z80_OPCODE(74, true, "LD (IY + %n), H", { LD8_addrreg_offset_valuereg(m_registers.IY, m_registers.H()); })
Z80_OPCODE(75, true, "LD (IY + %n), L", { LD8_addrreg_offset_valuereg(m_registers.IY, m_registers.L()); })
Z80_OPCODE(76, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(77, true, "LD (IY + %n), A", { LD8_addrreg_offset_valuereg(m_registers.IY, m_registers.A()); })
Z80_OPCODE(78, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(79, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(7A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(7B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(7C, true, "LD A, IYH", { LD8_reg_reg(&m_registers.A(), m_registers.IYH()); })
Z80_OPCODE(7D, true, "LD A, IYL", { LD8_reg_reg(&m_registers.A(), m_registers.IYL()); })
Z80_OPCODE(7E, true, "LD A, (IY + %n)", { LD8_reg_addrreg_offset(&m_registers.A(), m_registers.IY); })
Z80_OPCODE(7F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(80, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(81, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(82, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(83, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(84, true, "ADD A, IYH", { ADD8_reg_reg(&m_registers.A(), m_registers.IYH(), 0); })
Z80_OPCODE(85, true, "ADD A, IYL", { ADD8_reg_reg(&m_registers.A(), m_registers.IYL(), 0); })
Z80_OPCODE(86, true, "ADD A, (IY + %n)", { ADD8_reg_addrreg_offset(&m_registers.A(), m_registers.IY, 0); })
Z80_OPCODE(87, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(88, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(89, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8C, true, "ADC A, IYH", { ADD8_reg_reg(&m_registers.A(), m_registers.IYH(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8D, true, "ADC A, IYL", { ADD8_reg_reg(&m_registers.A(), m_registers.IYL(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8E, true, "ADC A, (IY + %n)", { ADD8_reg_addrreg_offset(&m_registers.A(), m_registers.IY, m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(90, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(91, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(92, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(93, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(94, true, "SUB IYH", { SUB8_reg(m_registers.IYH(), 0); })
Z80_OPCODE(95, true, "SUB IYL", { SUB8_reg(m_registers.IYL(), 0); })
Z80_OPCODE(96, true, "SUB (IY + %n)", { SUB8_addrreg_offset(m_registers.IY, 0); })
Z80_OPCODE(97, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(98, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(99, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9C, true, "SBC A, IYH", { SUB8_reg(m_registers.IYH(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9D, true, "SBC A, IYL", { SUB8_reg(m_registers.IYL(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9E, true, "SBC A, (IY + %n)", { SUB8_addrreg_offset(m_registers.IY, m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A4, true, "AND IYH", { AND_reg(m_registers.IYH()); })
Z80_OPCODE(A5, true, "AND IYL", { AND_reg(m_registers.IYL()); })
Z80_OPCODE(A6, true, "AND (IY + %n)", { AND_addrreg_offset(m_registers.IY); })
Z80_OPCODE(A7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(AA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(AB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(AC, true, "XOR IYH", { XOR_reg(m_registers.IYH()); })
Z80_OPCODE(AD, true, "XOR IYL", { XOR_reg(m_registers.IYL()); })
Z80_OPCODE(AE, true, "XOR (IY + %n)", { XOR_addrreg_offset(m_registers.IY); })
Z80_OPCODE(AF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B4, true, "OR IYH", { OR_reg(m_registers.IYH()); })
Z80_OPCODE(B5, true, "OR IYL", { OR_reg(m_registers.IYL()); })
Z80_OPCODE(B6, true, "OR (IY + %n)", { OR_addrreg_offset(m_registers.IY); })
Z80_OPCODE(B7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(BA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(BB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(BC, true, "CP IYH", { CP_reg(m_registers.IYH()); })
Z80_OPCODE(BD, true, "CP IYL", { CP_reg(m_registers.IYL()); })
Z80_OPCODE(BE, true, "CP (IY + %n)", { CP_addrreg_offset(m_registers.IY); })
Z80_OPCODE(BF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CB, false, "<CB prefix>", { ProcessPrefixByte(0xCB); })
Z80_OPCODE(CC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E1, true, "POP IY", { Pop(&m_registers.IY); })
Z80_OPCODE(E2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E3, true, "EX (SP), IY", { EX_addrreg_reg(m_registers.SP, &m_registers.IY); })
Z80_OPCODE(E4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E5, true, "PUSH IY", { Push(m_registers.IY); })
Z80_OPCODE(E6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E9, true, "JP (IY)", { JP_reg(m_registers.IY); })
Z80_OPCODE(EA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(ED, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F9, true, "LD SP, IY", { LD16_reg_reg(&m_registers.SP, m_registers.IY); })
Z80_OPCODE(FA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
