//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

#ifndef _CPCCRTC_H_
#define _CPCCRTC_H_


#include "cpcSubSystem.h"


namespace CPC {


    /**
    ** It emulates the 6845 CRTC chip. It was built by several manufacturers (UMC, Hitachi, Motorola and Amstrad) with slight
    ** differences between them.
    ** This chip along with the Gate-Array are responsible for generating the correct video signal that is sent to the Amstrad monitor.
    ** @par
    ** The CRTC was a commercial chip that was used in several machines including the Amstrad CPC.
    ** Its goal is 'simply' to generate memory addresses and HSYNC/VSYNC signals. The Gate-Array
    ** then reads the memory at these addresses and generates the video signal.
    ** @par
    ** The CRTC has several internal registers to configure the addresses it generates. However,
    ** only two are exposed to other components: one to select the internal register and other
    ** to read/write to the selected internal register.
    */
    class CCrtc : public CSubSystem
    {
    public:

        enum ERegister
        {
            HORIZONTAL_TOTAL = 0,           // [8 bits] Total screen width in characters, minus one. It should always be 63 (which means 64 characters). 1 character == 1us on the CPC.
            HORIZONTAL_DISPLAYED = 1,       // [8 bits] Number of characters displayed horizontally.
            HORIZONTAL_SYNC_POSITION = 2,   // [8 bits] When HSYNC signal starts, in characters.
            SYNC_WIDTHS = 3,                // [Lower 4 bits] HSYNC width in characters. [Higher 4 bits] VSYNC width in scan lines.
            VERTICAL_TOTAL = 4,             // [7 bits] Total screen height in characters, minus one.
            VERTICAL_TOTAL_ADJUST = 5,      // [5 bits, write-only] Number of additional scan lines needed to complete an entire frame. Can be used for smooth vertical scrolling.
            VERTICAL_DISPLAYED = 6,         // [7 bits] Number of characters displayed vertically.
            VERTICAL_SYNC_POSITION = 7,     // [7 bits] When VSYNC signal starts, in characters.
            INTERLACE_MODE_AND_SKEW = 8,    // This register is used to select the operating modes of the UM6845R and is configured as follows: (see UM6845 datasheet).
            MAXIMUM_SCAN_LINE_ADDRESS = 9,  // [5 bits] Number of scan lines per character row, including spacing, minus one.
            CURSOR_START_RASTER = 10,       // These 5-bit registers select the starting and edning scan lines for the cursor. In addition, bits 5 and 6 of R10 are used to select the cursor mode, as follows: (see UM6845 datasheet).
            CURSOR_END_RASTER = 11,         // "            "            "
            START_ADDRESS_HIGH = 12,        // These registers together comprise a 14-bit register containing the memory address of the first character of the displayed scan line (character on the top left of the video display, as in Figure 4). ...
            START_ADDRESS_LOW = 13,         // ... Subsequent memory addressess are generated by the UM6845R as a result of CCLK input pulses. Scrolling of the display is accomplished by changing R12 and R13 to the memory address associated with the first character of the desired line of text to be displayed first. Entire pages of text may be scrolled or changed as well via R12 and R13.
            CURSOR_ADDRESS_HIGH = 14,       // These registers together comprise a 14-bit register containing the memory address of the current cursor position. When the video display scan counter (MA lines) matches the contents of this register, ...
            CURSOR_ADDRESS_LOW = 15,        // ... and when the scan line counter (RA lines) falls within the bounds set by R10 and R11, then the CURSOR output becomes active. Bit 5 of the Mode Control Register (R8) may be used to delay the CURSOR output by a full CCLK time to accomodate slow access memories.
            LIGHTPEN_ADDRESS_HIGH = 16,     // [Not used] These registers together comprise a 14-bit register whose contents is the light pen strobe position, in terms of the video display address at which the strobe occured. When the LPEN input changes ...
            LIGHTPEN_ADDRESS_LOW = 17,      // [Not used] ... from low to high on the next negative-going edge of CCLK the contents of the internal scan counter are stored in registers R16 and R17.

            NUM_REGISTERS,
            INVALID_REGISTER = 0xFFFFFFFF
        };

        struct SGeneratedAddress
        {
            cpcWord MA;    // Memory Address, 14 bits.
            cpcByte RA;    // Raster Address, 5 bits.
        };


        CCrtc(CMachine *pMachine);
        virtual                ~CCrtc() { FreeVars(); }

        /** Resets the subsystem. */
        virtual void            Reset();

        /** Returns the current value of the given internal register. */
        inline cpcByte          GetRegisterValue(ERegister eRegister) const { return m_anRegisters[eRegister]; }

        /** Returns the current state of the DISPLAY_ENABLED signal.
        *** On the CPC, the Gate-Array uses it to generate video signal. If enabled, it reads pixel data from RAM. Otherwise, it uses the border color. */
        bool                    GetDisplayEnabledState() const { return (m_bDisplayEnabledH && m_bDisplayEnabledV); }
        /** Returns the current state of the HSYNC signal. */
        bool                    GetHSyncState() const { return m_bHSyncState; }
        /** Returns the current state of the VSYNC signal. */
        bool                    GetVSyncState() const { return m_bVSyncState; }
        /** Returns the current state of the VSYNC signal. */
        cpcByte                 GetCurrentVCharacter() const { return m_nCurrentVCharacter; }
        /** Returns the current memory address. */
        const SGeneratedAddress& GetCurrentAddress() const { return m_currentAddress; }

        /** We are notified that another subsytem is trying to write a byte to us.
        *** Usually it's the CPU through an OUT instruction. */
        virtual void            RespondToWritePortRequest(cpcWord nPort, cpcByte nValue);

        /** Runs the CRTC for the given number of cycles. */
        void                    Run(unsigned nNumCycles);


    private:

        typedef                 CSubSystem                inherited;

        static const cpcByte    s_registerMasks[NUM_REGISTERS];


        void                    ResetVars();
        void                    FreeVars();

        void                    SelectRegister(ERegister eRegister);
        void                    WriteSelectedRegister(cpcByte nValue);

        void                    UpdateHorizontal();
        void                    UpdateVertical();


        /** The internal registers. */
        cpcByte                 m_anRegisters[NUM_REGISTERS];
        /** The currently selected internal register. */
        ERegister               m_eSelectedRegister;

        cpcByte                 m_nCurrentHCharacter;       // A.k.a. HCC or C0.
        cpcByte                 m_nCurrentVCharacter;       // A.k.a. VCC or C4.
        cpcByte                 m_nCurrentScanLine;         // A.k.a. VLC or C9.
        cpcByte                 m_nScanLinesForVSyncOff;
        cpcByte                 m_nExtraScanLinesCounter;
        SGeneratedAddress       m_currentAddress;

        bool                    m_bDisplayEnabledH;
        bool                    m_bDisplayEnabledV;
        bool                    m_bHSyncState;
        bool                    m_bVSyncState;

    };


} //namespace CPC

#endif // _CPCCRTC_H_
