//------------------------------------------------------------------------------
// *** DO NOT INCLUDE DIRECTLY ***
//
// These macros generate code and populate several tables related to opcodes automatically.
//------------------------------------------------------------------------------

Z80_OPCODE(00, true, "NOP", "", "", TIMING_F4, { /* Do nothing. */ })
Z80_OPCODE(01, true, "LD", "BC", "%nn", TIMING_F4M3M3, { LD16_reg_nn(&m_registers.BC); })
Z80_OPCODE(02, true, "LD", "(BC)", "A", TIMING_F4M3, { LD8_addrreg_valuereg(m_registers.BC, m_registers.A()); })
Z80_OPCODE(03, true, "INC", "BC", "", TIMING_F6, { INC16_reg(&m_registers.BC); })
Z80_OPCODE(04, true, "INC", "B", "", TIMING_F4, { INC8_reg(&m_registers.B()); })
Z80_OPCODE(05, true, "DEC", "B", "", TIMING_F4, { DEC8_reg(&m_registers.B()); })
Z80_OPCODE(06, true, "LD", "B", "%n", TIMING_F4M3, { LD8_reg_n(&m_registers.B()); })
Z80_OPCODE(07, true, "RLCA", "", "", TIMING_F4, { RLCA(); })
Z80_OPCODE(08, true, "EX", "AF", "AF'", TIMING_F4, { EX_reg_reg(&m_registers.AF, &m_registers.altAF); })
Z80_OPCODE(09, true, "ADD", "HL", "BC", TIMING_F4I4I3, { ADD16_reg_reg(&m_registers.HL, m_registers.BC); })
Z80_OPCODE(0A, true, "LD", "A", "(BC)", TIMING_F4M3, { LD8_reg_mem(&m_registers.A(), m_registers.BC); })
Z80_OPCODE(0B, true, "DEC", "BC", "", TIMING_F6, { DEC16_reg(&m_registers.BC); })
Z80_OPCODE(0C, true, "INC", "C", "", TIMING_F4, { INC8_reg(&m_registers.C()); })
Z80_OPCODE(0D, true, "DEC", "C", "", TIMING_F4, { DEC8_reg(&m_registers.C()); })
Z80_OPCODE(0E, true, "LD", "C", "%n", TIMING_F4M3, { LD8_reg_n(&m_registers.C()); })
Z80_OPCODE(0F, true, "RRCA", "", "", TIMING_F4, { RRCA(); })
Z80_OPCODE(10, true, "DJNZ", "%n", "", TIMING_F5M3, { DJNZ_n(); })
Z80_OPCODE(11, true, "LD", "DE", "%nn", TIMING_F4M3M3, { LD16_reg_nn(&m_registers.DE); })
Z80_OPCODE(12, true, "LD", "(DE)", "A", TIMING_F4M3, { LD8_addrreg_valuereg(m_registers.DE, m_registers.A()); })
Z80_OPCODE(13, true, "INC", "DE", "", TIMING_F6, { INC16_reg(&m_registers.DE); })
Z80_OPCODE(14, true, "INC", "D", "", TIMING_F4, { INC8_reg(&m_registers.D()); })
Z80_OPCODE(15, true, "DEC", "D", "", TIMING_F4, { DEC8_reg(&m_registers.D()); })
Z80_OPCODE(16, true, "LD", "D", "%n", TIMING_F4M3, { LD8_reg_n(&m_registers.D()); })
Z80_OPCODE(17, true, "RLA", "", "", TIMING_F4, { RLA(); })
Z80_OPCODE(18, true, "JR", "%n", "", TIMING_F4M3I5, { JR_n(); })
Z80_OPCODE(19, true, "ADD", "HL", "DE", TIMING_F4I4I3, { ADD16_reg_reg(&m_registers.HL, m_registers.DE); })
Z80_OPCODE(1A, true, "LD", "A", "(DE)", TIMING_F4M3, { LD8_reg_mem(&m_registers.A(), m_registers.DE); })
Z80_OPCODE(1B, true, "DEC", "DE", "", TIMING_F6, { DEC16_reg(&m_registers.DE); })
Z80_OPCODE(1C, true, "INC", "E", "", TIMING_F4, { INC8_reg(&m_registers.E()); })
Z80_OPCODE(1D, true, "DEC", "E", "", TIMING_F4, { DEC8_reg(&m_registers.E()); })
Z80_OPCODE(1E, true, "LD", "E", "%n", TIMING_F4M3, { LD8_reg_n(&m_registers.E()); })
Z80_OPCODE(1F, true, "RRA", "", "", TIMING_F4, { RRA(); })
Z80_OPCODE(20, true, "JR", "NZ", "%n", TIMING_F4M3, { JR_condition_n(!m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(21, true, "LD", "HL", "%nn", TIMING_F4M3M3, { LD16_reg_nn(&m_registers.HL); })
Z80_OPCODE(22, true, "LD", "(%nn)", "HL", TIMING_F4M3M3M3M3, { LD16_addrnn_reg(m_registers.HL); })
Z80_OPCODE(23, true, "INC", "HL", "", TIMING_F6, { INC16_reg(&m_registers.HL); })
Z80_OPCODE(24, true, "INC", "H", "", TIMING_F4, { INC8_reg(&m_registers.H()); })
Z80_OPCODE(25, true, "DEC", "H", "", TIMING_F4, { DEC8_reg(&m_registers.H()); })
Z80_OPCODE(26, true, "LD", "H", "%n", TIMING_F4M3, { LD8_reg_n(&m_registers.H()); })
Z80_OPCODE(27, true, "DAA", "", "", TIMING_F4, { DAA(); })
Z80_OPCODE(28, true, "JR", "Z", "%n", TIMING_F4M3, { JR_condition_n(m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(29, true, "ADD", "HL", "HL", TIMING_F4I4I3, { ADD16_reg_reg(&m_registers.HL, m_registers.HL); })
Z80_OPCODE(2A, true, "LD", "HL", "(%nn)", TIMING_F4M3M3M3M3, { LD16_reg_addrnn(&m_registers.HL); })
Z80_OPCODE(2B, true, "DEC", "HL", "", TIMING_F6, { DEC16_reg(&m_registers.HL); })
Z80_OPCODE(2C, true, "INC", "L", "", TIMING_F4, { INC8_reg(&m_registers.L()); })
Z80_OPCODE(2D, true, "DEC", "L", "", TIMING_F4, { DEC8_reg(&m_registers.L()); })
Z80_OPCODE(2E, true, "LD", "L", "%n", TIMING_F4M3, { LD8_reg_n(&m_registers.L()); })
Z80_OPCODE(2F, true, "CPL", "", "", TIMING_F4, { CPL(); })
Z80_OPCODE(30, true, "JR", "NC", "%n", TIMING_F4M3, { JR_condition_n(!m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(31, true, "LD", "SP", "%nn", TIMING_F4M3M3, { LD16_reg_nn(&m_registers.SP); })
Z80_OPCODE(32, true, "LD", "(%nn)", "A", TIMING_F4M3M3M3, { LD8_addrnn_reg(m_registers.A()); })
Z80_OPCODE(33, true, "INC", "SP", "", TIMING_F6, { INC16_reg(&m_registers.SP); })
Z80_OPCODE(34, true, "INC", "(HL)", "", TIMING_F4M4M3, { INC8_addrreg(m_registers.HL); })
Z80_OPCODE(35, true, "DEC", "(HL)", "", TIMING_F4M4M3, { DEC8_addrreg(m_registers.HL); })
Z80_OPCODE(36, true, "LD", "(HL)", "%n", TIMING_F4M3M3, { LD8_addrreg_n(m_registers.HL); })
Z80_OPCODE(37, true, "SCF", "", "", TIMING_F4, { SCF(); })
Z80_OPCODE(38, true, "JR", "C", "%n", TIMING_F4M3, { JR_condition_n(m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(39, true, "ADD", "HL", "SP", TIMING_F4I4I3, { ADD16_reg_reg(&m_registers.HL, m_registers.SP); })
Z80_OPCODE(3A, true, "LD", "A", "(%nn)", TIMING_F4M3M3M3, { LD8_reg_addrnn(&m_registers.A()); })
Z80_OPCODE(3B, true, "DEC", "SP", "", TIMING_F6, { DEC16_reg(&m_registers.SP); })
Z80_OPCODE(3C, true, "INC", "A", "", TIMING_F4, { INC8_reg(&m_registers.A()); })
Z80_OPCODE(3D, true, "DEC", "A", "", TIMING_F4, { DEC8_reg(&m_registers.A()); })
Z80_OPCODE(3E, true, "LD", "A", "%n", TIMING_F4M3, { LD8_reg_n(&m_registers.A()); })
Z80_OPCODE(3F, true, "CCF", "", "", TIMING_F4, { CCF(); })
Z80_OPCODE(40, true, "LD", "B", "B", TIMING_F4, { LD8_reg_reg(&m_registers.B(), m_registers.B()); })
Z80_OPCODE(41, true, "LD", "B", "C", TIMING_F4, { LD8_reg_reg(&m_registers.B(), m_registers.C()); })
Z80_OPCODE(42, true, "LD", "B", "D", TIMING_F4, { LD8_reg_reg(&m_registers.B(), m_registers.D()); })
Z80_OPCODE(43, true, "LD", "B", "E", TIMING_F4, { LD8_reg_reg(&m_registers.B(), m_registers.E()); })
Z80_OPCODE(44, true, "LD", "B", "H", TIMING_F4, { LD8_reg_reg(&m_registers.B(), m_registers.H()); })
Z80_OPCODE(45, true, "LD", "B", "L", TIMING_F4, { LD8_reg_reg(&m_registers.B(), m_registers.L()); })
Z80_OPCODE(46, true, "LD", "B", "(HL)", TIMING_F4M3, { LD8_reg_addrreg(&m_registers.B(), m_registers.HL); })
Z80_OPCODE(47, true, "LD", "B", "A", TIMING_F4, { LD8_reg_reg(&m_registers.B(), m_registers.A()); })
Z80_OPCODE(48, true, "LD", "C", "B", TIMING_F4, { LD8_reg_reg(&m_registers.C(), m_registers.B()); })
Z80_OPCODE(49, true, "LD", "C", "C", TIMING_F4, { LD8_reg_reg(&m_registers.C(), m_registers.C()); })
Z80_OPCODE(4A, true, "LD", "C", "D", TIMING_F4, { LD8_reg_reg(&m_registers.C(), m_registers.D()); })
Z80_OPCODE(4B, true, "LD", "C", "E", TIMING_F4, { LD8_reg_reg(&m_registers.C(), m_registers.E()); })
Z80_OPCODE(4C, true, "LD", "C", "H", TIMING_F4, { LD8_reg_reg(&m_registers.C(), m_registers.H()); })
Z80_OPCODE(4D, true, "LD", "C", "L", TIMING_F4, { LD8_reg_reg(&m_registers.C(), m_registers.L()); })
Z80_OPCODE(4E, true, "LD", "C", "(HL)", TIMING_F4M3, { LD8_reg_addrreg(&m_registers.C(), m_registers.HL); })
Z80_OPCODE(4F, true, "LD", "C", "A", TIMING_F4, { LD8_reg_reg(&m_registers.C(), m_registers.A()); })
Z80_OPCODE(50, true, "LD", "D", "B", TIMING_F4, { LD8_reg_reg(&m_registers.D(), m_registers.B()); })
Z80_OPCODE(51, true, "LD", "D", "C", TIMING_F4, { LD8_reg_reg(&m_registers.D(), m_registers.C()); })
Z80_OPCODE(52, true, "LD", "D", "D", TIMING_F4, { LD8_reg_reg(&m_registers.D(), m_registers.D()); })
Z80_OPCODE(53, true, "LD", "D", "E", TIMING_F4, { LD8_reg_reg(&m_registers.D(), m_registers.E()); })
Z80_OPCODE(54, true, "LD", "D", "H", TIMING_F4, { LD8_reg_reg(&m_registers.D(), m_registers.H()); })
Z80_OPCODE(55, true, "LD", "D", "L", TIMING_F4, { LD8_reg_reg(&m_registers.D(), m_registers.L()); })
Z80_OPCODE(56, true, "LD", "D", "(HL)", TIMING_F4M3, { LD8_reg_addrreg(&m_registers.D(), m_registers.HL); })
Z80_OPCODE(57, true, "LD", "D", "A", TIMING_F4, { LD8_reg_reg(&m_registers.D(), m_registers.A()); })
Z80_OPCODE(58, true, "LD", "E", "B", TIMING_F4, { LD8_reg_reg(&m_registers.E(), m_registers.B()); })
Z80_OPCODE(59, true, "LD", "E", "C", TIMING_F4, { LD8_reg_reg(&m_registers.E(), m_registers.C()); })
Z80_OPCODE(5A, true, "LD", "E", "D", TIMING_F4, { LD8_reg_reg(&m_registers.E(), m_registers.D()); })
Z80_OPCODE(5B, true, "LD", "E", "E", TIMING_F4, { LD8_reg_reg(&m_registers.E(), m_registers.E()); })
Z80_OPCODE(5C, true, "LD", "E", "H", TIMING_F4, { LD8_reg_reg(&m_registers.E(), m_registers.H()); })
Z80_OPCODE(5D, true, "LD", "E", "L", TIMING_F4, { LD8_reg_reg(&m_registers.E(), m_registers.L()); })
Z80_OPCODE(5E, true, "LD", "E", "(HL)", TIMING_F4M3, { LD8_reg_addrreg(&m_registers.E(), m_registers.HL); })
Z80_OPCODE(5F, true, "LD", "E", "A", TIMING_F4, { LD8_reg_reg(&m_registers.E(), m_registers.A()); })
Z80_OPCODE(60, true, "LD", "H", "B", TIMING_F4, { LD8_reg_reg(&m_registers.H(), m_registers.B()); })
Z80_OPCODE(61, true, "LD", "H", "C", TIMING_F4, { LD8_reg_reg(&m_registers.H(), m_registers.C()); })
Z80_OPCODE(62, true, "LD", "H", "D", TIMING_F4, { LD8_reg_reg(&m_registers.H(), m_registers.D()); })
Z80_OPCODE(63, true, "LD", "H", "E", TIMING_F4, { LD8_reg_reg(&m_registers.H(), m_registers.E()); })
Z80_OPCODE(64, true, "LD", "H", "H", TIMING_F4, { LD8_reg_reg(&m_registers.H(), m_registers.H()); })
Z80_OPCODE(65, true, "LD", "H", "L", TIMING_F4, { LD8_reg_reg(&m_registers.H(), m_registers.L()); })
Z80_OPCODE(66, true, "LD", "H", "(HL)", TIMING_F4M3, { LD8_reg_addrreg(&m_registers.H(), m_registers.HL); })
Z80_OPCODE(67, true, "LD", "H", "A", TIMING_F4, { LD8_reg_reg(&m_registers.H(), m_registers.A()); })
Z80_OPCODE(68, true, "LD", "L", "B", TIMING_F4, { LD8_reg_reg(&m_registers.L(), m_registers.B()); })
Z80_OPCODE(69, true, "LD", "L", "C", TIMING_F4, { LD8_reg_reg(&m_registers.L(), m_registers.C()); })
Z80_OPCODE(6A, true, "LD", "L", "D", TIMING_F4, { LD8_reg_reg(&m_registers.L(), m_registers.D()); })
Z80_OPCODE(6B, true, "LD", "L", "E", TIMING_F4, { LD8_reg_reg(&m_registers.L(), m_registers.E()); })
Z80_OPCODE(6C, true, "LD", "L", "H", TIMING_F4, { LD8_reg_reg(&m_registers.L(), m_registers.H()); })
Z80_OPCODE(6D, true, "LD", "L", "L", TIMING_F4, { LD8_reg_reg(&m_registers.L(), m_registers.L()); })
Z80_OPCODE(6E, true, "LD", "L", "(HL)", TIMING_F4M3, { LD8_reg_addrreg(&m_registers.L(), m_registers.HL); })
Z80_OPCODE(6F, true, "LD", "L", "A", TIMING_F4, { LD8_reg_reg(&m_registers.L(), m_registers.A()); })
Z80_OPCODE(70, true, "LD", "(HL)", "B", TIMING_F4M3, { LD8_addrreg_valuereg(m_registers.HL, m_registers.B()); })
Z80_OPCODE(71, true, "LD", "(HL)", "C", TIMING_F4M3, { LD8_addrreg_valuereg(m_registers.HL, m_registers.C()); })
Z80_OPCODE(72, true, "LD", "(HL)", "D", TIMING_F4M3, { LD8_addrreg_valuereg(m_registers.HL, m_registers.D()); })
Z80_OPCODE(73, true, "LD", "(HL)", "E", TIMING_F4M3, { LD8_addrreg_valuereg(m_registers.HL, m_registers.E()); })
Z80_OPCODE(74, true, "LD", "(HL)", "H", TIMING_F4M3, { LD8_addrreg_valuereg(m_registers.HL, m_registers.H()); })
Z80_OPCODE(75, true, "LD", "(HL)", "L", TIMING_F4M3, { LD8_addrreg_valuereg(m_registers.HL, m_registers.L()); })
Z80_OPCODE(76, true, "HALT", "", "", TIMING_F4, { HALT(); })
Z80_OPCODE(77, true, "LD", "(HL)", "A", TIMING_F4M3, { LD8_addrreg_valuereg(m_registers.HL, m_registers.A()); })
Z80_OPCODE(78, true, "LD", "A", "B", TIMING_F4, { LD8_reg_reg(&m_registers.A(), m_registers.B()); })
Z80_OPCODE(79, true, "LD", "A", "C", TIMING_F4, { LD8_reg_reg(&m_registers.A(), m_registers.C()); })
Z80_OPCODE(7A, true, "LD", "A", "D", TIMING_F4, { LD8_reg_reg(&m_registers.A(), m_registers.D()); })
Z80_OPCODE(7B, true, "LD", "A", "E", TIMING_F4, { LD8_reg_reg(&m_registers.A(), m_registers.E()); })
Z80_OPCODE(7C, true, "LD", "A", "H", TIMING_F4, { LD8_reg_reg(&m_registers.A(), m_registers.H()); })
Z80_OPCODE(7D, true, "LD", "A", "L", TIMING_F4, { LD8_reg_reg(&m_registers.A(), m_registers.L()); })
Z80_OPCODE(7E, true, "LD", "A", "(HL)", TIMING_F4M3, { LD8_reg_addrreg(&m_registers.A(), m_registers.HL); })
Z80_OPCODE(7F, true, "LD", "A", "A", TIMING_F4, { LD8_reg_reg(&m_registers.A(), m_registers.A()); })
Z80_OPCODE(80, true, "ADD", "A", "B", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.B(), 0); })
Z80_OPCODE(81, true, "ADD", "A", "C", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.C(), 0); })
Z80_OPCODE(82, true, "ADD", "A", "D", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.D(), 0); })
Z80_OPCODE(83, true, "ADD", "A", "E", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.E(), 0); })
Z80_OPCODE(84, true, "ADD", "A", "H", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.H(), 0); })
Z80_OPCODE(85, true, "ADD", "A", "L", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.L(), 0); })
Z80_OPCODE(86, true, "ADD", "A", "(HL)", TIMING_F4M3, { ADD8_reg_addrreg(&m_registers.A(), m_registers.HL, 0); })
Z80_OPCODE(87, true, "ADD", "A", "A", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.A(), 0); })
Z80_OPCODE(88, true, "ADC", "A", "B", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.B(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(89, true, "ADC", "A", "C", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.C(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8A, true, "ADC", "A", "D", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.D(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8B, true, "ADC", "A", "E", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.E(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8C, true, "ADC", "A", "H", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.H(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8D, true, "ADC", "A", "L", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.L(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8E, true, "ADC", "A", "(HL)", TIMING_F4M3, { ADD8_reg_addrreg(&m_registers.A(), m_registers.HL, m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8F, true, "ADC", "A", "A", TIMING_F4, { ADD8_reg_reg(&m_registers.A(), m_registers.A(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(90, true, "SUB", "B", "", TIMING_F4, { SUB8_reg(m_registers.B(), 0); })
Z80_OPCODE(91, true, "SUB", "C", "", TIMING_F4, { SUB8_reg(m_registers.C(), 0); })
Z80_OPCODE(92, true, "SUB", "D", "", TIMING_F4, { SUB8_reg(m_registers.D(), 0); })
Z80_OPCODE(93, true, "SUB", "E", "", TIMING_F4, { SUB8_reg(m_registers.E(), 0); })
Z80_OPCODE(94, true, "SUB", "H", "", TIMING_F4, { SUB8_reg(m_registers.H(), 0); })
Z80_OPCODE(95, true, "SUB", "L", "", TIMING_F4, { SUB8_reg(m_registers.L(), 0); })
Z80_OPCODE(96, true, "SUB", "(HL)", "", TIMING_F4M3, { SUB8_addrreg(m_registers.HL, 0); })
Z80_OPCODE(97, true, "SUB", "A", "", TIMING_F4, { SUB8_reg(m_registers.A(), 0); })
Z80_OPCODE(98, true, "SBC", "A", "B", TIMING_F4, { SUB8_reg(m_registers.B(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(99, true, "SBC", "A", "C", TIMING_F4, { SUB8_reg(m_registers.C(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9A, true, "SBC", "A", "D", TIMING_F4, { SUB8_reg(m_registers.D(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9B, true, "SBC", "A", "E", TIMING_F4, { SUB8_reg(m_registers.E(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9C, true, "SBC", "A", "H", TIMING_F4, { SUB8_reg(m_registers.H(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9D, true, "SBC", "A", "L", TIMING_F4, { SUB8_reg(m_registers.L(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9E, true, "SBC", "A", "(HL)", TIMING_F4M3, { SUB8_addrreg(m_registers.HL, m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9F, true, "SBC", "A", "A", TIMING_F4, { SUB8_reg(m_registers.A(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(A0, true, "AND", "B", "", TIMING_F4, { AND_reg(m_registers.B()); })
Z80_OPCODE(A1, true, "AND", "C", "", TIMING_F4, { AND_reg(m_registers.C()); })
Z80_OPCODE(A2, true, "AND", "D", "", TIMING_F4, { AND_reg(m_registers.D()); })
Z80_OPCODE(A3, true, "AND", "E", "", TIMING_F4, { AND_reg(m_registers.E()); })
Z80_OPCODE(A4, true, "AND", "H", "", TIMING_F4, { AND_reg(m_registers.H()); })
Z80_OPCODE(A5, true, "AND", "L", "", TIMING_F4, { AND_reg(m_registers.L()); })
Z80_OPCODE(A6, true, "AND", "(HL)", "", TIMING_F4M3, { AND_addrreg(m_registers.HL); })
Z80_OPCODE(A7, true, "AND", "A", "", TIMING_F4, { AND_reg(m_registers.A()); })
Z80_OPCODE(A8, true, "XOR", "B", "", TIMING_F4, { XOR_reg(m_registers.B()); })
Z80_OPCODE(A9, true, "XOR", "C", "", TIMING_F4, { XOR_reg(m_registers.C()); })
Z80_OPCODE(AA, true, "XOR", "D", "", TIMING_F4, { XOR_reg(m_registers.D()); })
Z80_OPCODE(AB, true, "XOR", "E", "", TIMING_F4, { XOR_reg(m_registers.E()); })
Z80_OPCODE(AC, true, "XOR", "H", "", TIMING_F4, { XOR_reg(m_registers.H()); })
Z80_OPCODE(AD, true, "XOR", "L", "", TIMING_F4, { XOR_reg(m_registers.L()); })
Z80_OPCODE(AE, true, "XOR", "(HL)", "", TIMING_F4M3, { XOR_addrreg(m_registers.HL); })
Z80_OPCODE(AF, true, "XOR", "A", "", TIMING_F4, { XOR_reg(m_registers.A()); })
Z80_OPCODE(B0, true, "OR", "B", "", TIMING_F4, { OR_reg(m_registers.B()); })
Z80_OPCODE(B1, true, "OR", "C", "", TIMING_F4, { OR_reg(m_registers.C()); })
Z80_OPCODE(B2, true, "OR", "D", "", TIMING_F4, { OR_reg(m_registers.D()); })
Z80_OPCODE(B3, true, "OR", "E", "", TIMING_F4, { OR_reg(m_registers.E()); })
Z80_OPCODE(B4, true, "OR", "H", "", TIMING_F4, { OR_reg(m_registers.H()); })
Z80_OPCODE(B5, true, "OR", "L", "", TIMING_F4, { OR_reg(m_registers.L()); })
Z80_OPCODE(B6, true, "OR", "(HL)", "", TIMING_F4M3, { OR_addrreg(m_registers.HL); })
Z80_OPCODE(B7, true, "OR", "A", "", TIMING_F4, { OR_reg(m_registers.A()); })
Z80_OPCODE(B8, true, "CP", "B", "", TIMING_F4, { CP_reg(m_registers.B()); })
Z80_OPCODE(B9, true, "CP", "C", "", TIMING_F4, { CP_reg(m_registers.C()); })
Z80_OPCODE(BA, true, "CP", "D", "", TIMING_F4, { CP_reg(m_registers.D()); })
Z80_OPCODE(BB, true, "CP", "E", "", TIMING_F4, { CP_reg(m_registers.E()); })
Z80_OPCODE(BC, true, "CP", "H", "", TIMING_F4, { CP_reg(m_registers.H()); })
Z80_OPCODE(BD, true, "CP", "L", "", TIMING_F4, { CP_reg(m_registers.L()); })
Z80_OPCODE(BE, true, "CP", "(HL)", "", TIMING_F4M3, { CP_addrreg(m_registers.HL); })
Z80_OPCODE(BF, true, "CP", "A", "", TIMING_F4, { CP_reg(m_registers.A()); })
Z80_OPCODE(C0, true, "RET", "NZ", "", TIMING_F5, { RET_condition(!m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(C1, true, "POP", "BC", "", TIMING_F4M3M3, { POP(&m_registers.BC); })
Z80_OPCODE(C2, true, "JP", "NZ", "%nn", TIMING_F4M3M3, { JP_condition_nn(!m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(C3, true, "JP", "%nn", "", TIMING_F4M3M3, { JP_nn(); })
Z80_OPCODE(C4, true, "CALL", "NZ", "%nn", TIMING_F4M3, { CALL_condition_nn(!m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(C5, true, "PUSH", "BC", "", TIMING_F5M3M3, { PUSH(m_registers.BC); })
Z80_OPCODE(C6, true, "ADD", "A", "%n", TIMING_F4M3, { ADD8_reg_n(&m_registers.A(), 0); })
Z80_OPCODE(C7, true, "RST", "00h", "", TIMING_F5M3M3, { RST_p(0x00); })
Z80_OPCODE(C8, true, "RET", "Z", "", TIMING_F5, { RET_condition(m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(C9, true, "RET", "", "", TIMING_F4M3M3, { RET(); })
Z80_OPCODE(CA, true, "JP", "Z", "%nn", TIMING_F4M3M3, { JP_condition_nn(m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(CB, false, "<CB prefix>", "", "", TIMING_F4, { ProcessPrefixByte(0xCB); })
Z80_OPCODE(CC, true, "CALL", "Z", "%nn", TIMING_F4M3, { CALL_condition_nn(m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(CD, true, "CALL", "%nn", "", TIMING_F4M3M4M3M3, { CALL_nn(); })
Z80_OPCODE(CE, true, "ADC", "A", "%n", TIMING_F4M3, { ADD8_reg_n(&m_registers.A(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(CF, true, "RST", "08h", "", TIMING_F5M3M3, { RST_p(0x08); })
Z80_OPCODE(D0, true, "RET", "NC", "", TIMING_F5, { RET_condition(!m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(D1, true, "POP", "DE", "", TIMING_F4M3M3, { POP(&m_registers.DE); })
Z80_OPCODE(D2, true, "JP", "NC", "%nn", TIMING_F4M3M3, { JP_condition_nn(!m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(D3, true, "OUT", "(%n)", "A", TIMING_F4M3E4, { OUT_n(); })
Z80_OPCODE(D4, true, "CALL", "NC", "%nn", TIMING_F4M3, { CALL_condition_nn(!m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(D5, true, "PUSH", "DE", "", TIMING_F5M3M3, { PUSH(m_registers.DE); })
Z80_OPCODE(D6, true, "SUB", "%n", "", TIMING_F4M3, { SUB8_n(0); })
Z80_OPCODE(D7, true, "RST", "10h", "", TIMING_F5M3M3, { RST_p(0x10); })
Z80_OPCODE(D8, true, "RET", "C", "", TIMING_F5, { RET_condition(m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(D9, true, "EXX", "", "", TIMING_F4, { EXX(); })
Z80_OPCODE(DA, true, "JP", "C", "%nn", TIMING_F4M3M3, { JP_condition_nn(m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(DB, true, "IN", "A", "(%n)", TIMING_F4M3E4, { IN_n(); })
Z80_OPCODE(DC, true, "CALL", "C", "%nn", TIMING_F4M3, { CALL_condition_nn(m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(DD, false, "<DD prefix>", "", "", TIMING_F4, { ProcessPrefixByte(0xDD); })
Z80_OPCODE(DE, true, "SBC", "A", "%n", TIMING_F4M3, { SUB8_n(m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(DF, true, "RST", "18h", "", TIMING_F5M3M3, { RST_p(0x18); })
Z80_OPCODE(E0, true, "RET", "PO", "", TIMING_F5, { RET_condition(!m_registers.GetFlag(Registers::Flag_PV)); })
Z80_OPCODE(E1, true, "POP", "HL", "", TIMING_F4M3M3, { POP(&m_registers.HL); })
Z80_OPCODE(E2, true, "JP", "PO", "%nn", TIMING_F4M3M3, { JP_condition_nn(!m_registers.GetFlag(Registers::Flag_PV)); })
Z80_OPCODE(E3, true, "EX", "(SP)", "HL", TIMING_F4M3M4M3M5, { EX_addrreg_reg(m_registers.SP, &m_registers.HL); })
Z80_OPCODE(E4, true, "CALL", "PO", "%nn", TIMING_F4M3, { CALL_condition_nn(!m_registers.GetFlag(Registers::Flag_PV)); })
Z80_OPCODE(E5, true, "PUSH", "HL", "", TIMING_F5M3M3, { PUSH(m_registers.HL); })
Z80_OPCODE(E6, true, "AND", "%n", "", TIMING_F4M3, { AND_n(); })
Z80_OPCODE(E7, true, "RST", "20h", "", TIMING_F5M3M3, { RST_p(0x20); })
Z80_OPCODE(E8, true, "RET", "PE", "", TIMING_F5, { RET_condition(m_registers.GetFlag(Registers::Flag_PV)); })
Z80_OPCODE(E9, true, "JP", "(HL)", "", TIMING_F4, { JP_reg(m_registers.HL); })
Z80_OPCODE(EA, true, "JP", "PE", "%nn", TIMING_F4M3M3, { JP_condition_nn(m_registers.GetFlag(Registers::Flag_PV)); })
Z80_OPCODE(EB, true, "EX", "DE", "HL", TIMING_F4, { EX_reg_reg(&m_registers.DE, &m_registers.HL); })
Z80_OPCODE(EC, true, "CALL", "PE", "%nn", TIMING_F4M3, { CALL_condition_nn(m_registers.GetFlag(Registers::Flag_PV)); })
Z80_OPCODE(ED, false, "<ED prefix>", "", "", TIMING_F4, { ProcessPrefixByte(0xED); })
Z80_OPCODE(EE, true, "XOR", "%n", "", TIMING_F4M3, { XOR_n(); })
Z80_OPCODE(EF, true, "RST", "28h", "", TIMING_F5M3M3, { RST_p(0x28); })
Z80_OPCODE(F0, true, "RET", "P", "", TIMING_F5, { RET_condition(!m_registers.GetFlag(Registers::Flag_S)); })
Z80_OPCODE(F1, true, "POP", "AF", "", TIMING_F4M3M3, { POP(&m_registers.AF); })
Z80_OPCODE(F2, true, "JP", "P", "%nn", TIMING_F4M3M3, { JP_condition_nn(!m_registers.GetFlag(Registers::Flag_S)); })
Z80_OPCODE(F3, true, "DI", "", "", TIMING_F4, { DI(); })
Z80_OPCODE(F4, true, "CALL", "P", "%nn", TIMING_F4M3, { CALL_condition_nn(!m_registers.GetFlag(Registers::Flag_S)); })
Z80_OPCODE(F5, true, "PUSH", "AF", "", TIMING_F5M3M3, { PUSH(m_registers.AF); })
Z80_OPCODE(F6, true, "OR", "%n", "", TIMING_F4M3, { OR_n(); })
Z80_OPCODE(F7, true, "RST", "30h", "", TIMING_F5M3M3, { RST_p(0x30); })
Z80_OPCODE(F8, true, "RET", "M", "", TIMING_F5, { RET_condition(m_registers.GetFlag(Registers::Flag_S)); })
Z80_OPCODE(F9, true, "LD", "SP", "HL", TIMING_F6, { LD16_reg_reg(&m_registers.SP, m_registers.HL); })
Z80_OPCODE(FA, true, "JP", "M", "%nn", TIMING_F4M3M3, { JP_condition_nn(m_registers.GetFlag(Registers::Flag_S)); })
Z80_OPCODE(FB, true, "EI", "", "", TIMING_F4, { EI(); })
Z80_OPCODE(FC, true, "CALL", "M", "%nn", TIMING_F4M3, { CALL_condition_nn(m_registers.GetFlag(Registers::Flag_S)); })
Z80_OPCODE(FD, false, "<FD prefix>", "", "", TIMING_F4, { ProcessPrefixByte(0xFD); })
Z80_OPCODE(FE, true, "CP", "%n", "", TIMING_F4M3, { CP_n(); })
Z80_OPCODE(FF, true, "RST", "38h", "", TIMING_F5M3M3, { RST_p(0x38); })
