//------------------------------------------------------------------------------
// *** DO NOT INCLUDE DIRECTLY ***
//
// These macros generate code and populate several tables related to opcodes automatically.
//------------------------------------------------------------------------------

Z80_OPCODE(00, true, "RLC B", TIMING_F4, { RLC_reg(&m_registers.B()); })
Z80_OPCODE(01, true, "RLC C", TIMING_F4, { RLC_reg(&m_registers.C()); })
Z80_OPCODE(02, true, "RLC D", TIMING_F4, { RLC_reg(&m_registers.D()); })
Z80_OPCODE(03, true, "RLC E", TIMING_F4, { RLC_reg(&m_registers.E()); })
Z80_OPCODE(04, true, "RLC H", TIMING_F4, { RLC_reg(&m_registers.H()); })
Z80_OPCODE(05, true, "RLC L", TIMING_F4, { RLC_reg(&m_registers.L()); })
Z80_OPCODE(06, true, "RLC (HL)", TIMING_F4, { RLC_addrreg(m_registers.HL); })
Z80_OPCODE(07, true, "RLC A", TIMING_F4, { RLC_reg(&m_registers.A()); })
Z80_OPCODE(08, true, "RRC B", TIMING_F4, { RRC_reg(&m_registers.B()); })
Z80_OPCODE(09, true, "RRC C", TIMING_F4, { RRC_reg(&m_registers.C()); })
Z80_OPCODE(0A, true, "RRC D", TIMING_F4, { RRC_reg(&m_registers.D()); })
Z80_OPCODE(0B, true, "RRC E", TIMING_F4, { RRC_reg(&m_registers.E()); })
Z80_OPCODE(0C, true, "RRC H", TIMING_F4, { RRC_reg(&m_registers.H()); })
Z80_OPCODE(0D, true, "RRC L", TIMING_F4, { RRC_reg(&m_registers.L()); })
Z80_OPCODE(0E, true, "RRC (HL)", TIMING_F4, { RRC_addrreg(m_registers.HL); })
Z80_OPCODE(0F, true, "RRC A", TIMING_F4, { RRC_reg(&m_registers.A()); })
Z80_OPCODE(10, true, "RL B", TIMING_F4, { RL_reg(&m_registers.B()); })
Z80_OPCODE(11, true, "RL C", TIMING_F4, { RL_reg(&m_registers.C()); })
Z80_OPCODE(12, true, "RL D", TIMING_F4, { RL_reg(&m_registers.D()); })
Z80_OPCODE(13, true, "RL E", TIMING_F4, { RL_reg(&m_registers.E()); })
Z80_OPCODE(14, true, "RL H", TIMING_F4, { RL_reg(&m_registers.H()); })
Z80_OPCODE(15, true, "RL L", TIMING_F4, { RL_reg(&m_registers.L()); })
Z80_OPCODE(16, true, "RL (HL)", TIMING_F4, { RL_addrreg(m_registers.HL); })
Z80_OPCODE(17, true, "RL A", TIMING_F4, { RL_reg(&m_registers.A()); })
Z80_OPCODE(18, true, "RR B", TIMING_F4, { RR_reg(&m_registers.B()); })
Z80_OPCODE(19, true, "RR C", TIMING_F4, { RR_reg(&m_registers.C()); })
Z80_OPCODE(1A, true, "RR D", TIMING_F4, { RR_reg(&m_registers.D()); })
Z80_OPCODE(1B, true, "RR E", TIMING_F4, { RR_reg(&m_registers.E()); })
Z80_OPCODE(1C, true, "RR H", TIMING_F4, { RR_reg(&m_registers.H()); })
Z80_OPCODE(1D, true, "RR L", TIMING_F4, { RR_reg(&m_registers.L()); })
Z80_OPCODE(1E, true, "RR (HL)", TIMING_F4, { RR_addrreg(m_registers.HL); })
Z80_OPCODE(1F, true, "RR A", TIMING_F4, { RR_reg(&m_registers.A()); })
Z80_OPCODE(20, true, "SLA B", TIMING_F4, { SL_reg(&m_registers.B(), false); })
Z80_OPCODE(21, true, "SLA C", TIMING_F4, { SL_reg(&m_registers.C(), false); })
Z80_OPCODE(22, true, "SLA D", TIMING_F4, { SL_reg(&m_registers.D(), false); })
Z80_OPCODE(23, true, "SLA E", TIMING_F4, { SL_reg(&m_registers.E(), false); })
Z80_OPCODE(24, true, "SLA H", TIMING_F4, { SL_reg(&m_registers.H(), false); })
Z80_OPCODE(25, true, "SLA L", TIMING_F4, { SL_reg(&m_registers.L(), false); })
Z80_OPCODE(26, true, "SLA (HL)", TIMING_F4, { SL_addrreg(m_registers.HL, false); })
Z80_OPCODE(27, true, "SLA A", TIMING_F4, { SL_reg(&m_registers.A(), false); })
Z80_OPCODE(28, true, "SRA B", TIMING_F4, { SR_reg(&m_registers.B(), (m_registers.B() & 0x80) != 0); })
Z80_OPCODE(29, true, "SRA C", TIMING_F4, { SR_reg(&m_registers.C(), (m_registers.C() & 0x80) != 0); })
Z80_OPCODE(2A, true, "SRA D", TIMING_F4, { SR_reg(&m_registers.D(), (m_registers.D() & 0x80) != 0); })
Z80_OPCODE(2B, true, "SRA E", TIMING_F4, { SR_reg(&m_registers.E(), (m_registers.E() & 0x80) != 0); })
Z80_OPCODE(2C, true, "SRA H", TIMING_F4, { SR_reg(&m_registers.H(), (m_registers.H() & 0x80) != 0); })
Z80_OPCODE(2D, true, "SRA L", TIMING_F4, { SR_reg(&m_registers.L(), (m_registers.L() & 0x80) != 0); })
Z80_OPCODE(2E, true, "SRA (HL)", TIMING_F4, { SRA_addrreg(m_registers.HL); })
Z80_OPCODE(2F, true, "SRA A", TIMING_F4, { SR_reg(&m_registers.A(), (m_registers.A() & 0x80) != 0); })
Z80_OPCODE(30, true, "SLL B", TIMING_F4, { SL_reg(&m_registers.B(), true); })
Z80_OPCODE(31, true, "SLL C", TIMING_F4, { SL_reg(&m_registers.C(), true); })
Z80_OPCODE(32, true, "SLL D", TIMING_F4, { SL_reg(&m_registers.D(), true); })
Z80_OPCODE(33, true, "SLL E", TIMING_F4, { SL_reg(&m_registers.E(), true); })
Z80_OPCODE(34, true, "SLL H", TIMING_F4, { SL_reg(&m_registers.H(), true); })
Z80_OPCODE(35, true, "SLL L", TIMING_F4, { SL_reg(&m_registers.L(), true); })
Z80_OPCODE(36, true, "SLL (HL)", TIMING_F4, { SL_addrreg(m_registers.HL, true); })
Z80_OPCODE(37, true, "SLL A", TIMING_F4, { SL_reg(&m_registers.A(), true); })
Z80_OPCODE(38, true, "SRL B", TIMING_F4, { SR_reg(&m_registers.B(), false); })
Z80_OPCODE(39, true, "SRL C", TIMING_F4, { SR_reg(&m_registers.C(), false); })
Z80_OPCODE(3A, true, "SRL D", TIMING_F4, { SR_reg(&m_registers.D(), false); })
Z80_OPCODE(3B, true, "SRL E", TIMING_F4, { SR_reg(&m_registers.E(), false); })
Z80_OPCODE(3C, true, "SRL H", TIMING_F4, { SR_reg(&m_registers.H(), false); })
Z80_OPCODE(3D, true, "SRL L", TIMING_F4, { SR_reg(&m_registers.L(), false); })
Z80_OPCODE(3E, true, "SRL (HL)", TIMING_F4, { SRL_addrreg(m_registers.HL); })
Z80_OPCODE(3F, true, "SRL A", TIMING_F4, { SR_reg(&m_registers.A(), false); })
Z80_OPCODE(40, true, "BIT 0, B", TIMING_F4, { BIT_reg(0, m_registers.B()); })
Z80_OPCODE(41, true, "BIT 0, C", TIMING_F4, { BIT_reg(0, m_registers.C()); })
Z80_OPCODE(42, true, "BIT 0, D", TIMING_F4, { BIT_reg(0, m_registers.D()); })
Z80_OPCODE(43, true, "BIT 0, E", TIMING_F4, { BIT_reg(0, m_registers.E()); })
Z80_OPCODE(44, true, "BIT 0, H", TIMING_F4, { BIT_reg(0, m_registers.H()); })
Z80_OPCODE(45, true, "BIT 0, L", TIMING_F4, { BIT_reg(0, m_registers.L()); })
Z80_OPCODE(46, true, "BIT 0, (HL)", TIMING_F4, { BIT_addr(0, m_registers.HL.w); })
Z80_OPCODE(47, true, "BIT 0, A", TIMING_F4, { BIT_reg(0, m_registers.A()); })
Z80_OPCODE(48, true, "BIT 1, B", TIMING_F4, { BIT_reg(1, m_registers.B()); })
Z80_OPCODE(49, true, "BIT 1, C", TIMING_F4, { BIT_reg(1, m_registers.C()); })
Z80_OPCODE(4A, true, "BIT 1, D", TIMING_F4, { BIT_reg(1, m_registers.D()); })
Z80_OPCODE(4B, true, "BIT 1, E", TIMING_F4, { BIT_reg(1, m_registers.E()); })
Z80_OPCODE(4C, true, "BIT 1, H", TIMING_F4, { BIT_reg(1, m_registers.H()); })
Z80_OPCODE(4D, true, "BIT 1, L", TIMING_F4, { BIT_reg(1, m_registers.L()); })
Z80_OPCODE(4E, true, "BIT 1, (HL)", TIMING_F4, { BIT_addr(1, m_registers.HL.w); })
Z80_OPCODE(4F, true, "BIT 1, A", TIMING_F4, { BIT_reg(1, m_registers.A()); })
Z80_OPCODE(50, true, "BIT 2, B", TIMING_F4, { BIT_reg(2, m_registers.B()); })
Z80_OPCODE(51, true, "BIT 2, C", TIMING_F4, { BIT_reg(2, m_registers.C()); })
Z80_OPCODE(52, true, "BIT 2, D", TIMING_F4, { BIT_reg(2, m_registers.D()); })
Z80_OPCODE(53, true, "BIT 2, E", TIMING_F4, { BIT_reg(2, m_registers.E()); })
Z80_OPCODE(54, true, "BIT 2, H", TIMING_F4, { BIT_reg(2, m_registers.H()); })
Z80_OPCODE(55, true, "BIT 2, L", TIMING_F4, { BIT_reg(2, m_registers.L()); })
Z80_OPCODE(56, true, "BIT 2, (HL)", TIMING_F4, { BIT_addr(2, m_registers.HL.w); })
Z80_OPCODE(57, true, "BIT 2, A", TIMING_F4, { BIT_reg(2, m_registers.A()); })
Z80_OPCODE(58, true, "BIT 3, B", TIMING_F4, { BIT_reg(3, m_registers.B()); })
Z80_OPCODE(59, true, "BIT 3, C", TIMING_F4, { BIT_reg(3, m_registers.C()); })
Z80_OPCODE(5A, true, "BIT 3, D", TIMING_F4, { BIT_reg(3, m_registers.D()); })
Z80_OPCODE(5B, true, "BIT 3, E", TIMING_F4, { BIT_reg(3, m_registers.E()); })
Z80_OPCODE(5C, true, "BIT 3, H", TIMING_F4, { BIT_reg(3, m_registers.H()); })
Z80_OPCODE(5D, true, "BIT 3, L", TIMING_F4, { BIT_reg(3, m_registers.L()); })
Z80_OPCODE(5E, true, "BIT 3, (HL)", TIMING_F4, { BIT_addr(3, m_registers.HL.w); })
Z80_OPCODE(5F, true, "BIT 3, A", TIMING_F4, { BIT_reg(3, m_registers.A()); })
Z80_OPCODE(60, true, "BIT 4, B", TIMING_F4, { BIT_reg(4, m_registers.B()); })
Z80_OPCODE(61, true, "BIT 4, C", TIMING_F4, { BIT_reg(4, m_registers.C()); })
Z80_OPCODE(62, true, "BIT 4, D", TIMING_F4, { BIT_reg(4, m_registers.D()); })
Z80_OPCODE(63, true, "BIT 4, E", TIMING_F4, { BIT_reg(4, m_registers.E()); })
Z80_OPCODE(64, true, "BIT 4, H", TIMING_F4, { BIT_reg(4, m_registers.H()); })
Z80_OPCODE(65, true, "BIT 4, L", TIMING_F4, { BIT_reg(4, m_registers.L()); })
Z80_OPCODE(66, true, "BIT 4, (HL)", TIMING_F4, { BIT_addr(4, m_registers.HL.w); })
Z80_OPCODE(67, true, "BIT 4, A", TIMING_F4, { BIT_reg(4, m_registers.A()); })
Z80_OPCODE(68, true, "BIT 5, B", TIMING_F4, { BIT_reg(5, m_registers.B()); })
Z80_OPCODE(69, true, "BIT 5, C", TIMING_F4, { BIT_reg(5, m_registers.C()); })
Z80_OPCODE(6A, true, "BIT 5, D", TIMING_F4, { BIT_reg(5, m_registers.D()); })
Z80_OPCODE(6B, true, "BIT 5, E", TIMING_F4, { BIT_reg(5, m_registers.E()); })
Z80_OPCODE(6C, true, "BIT 5, H", TIMING_F4, { BIT_reg(5, m_registers.H()); })
Z80_OPCODE(6D, true, "BIT 5, L", TIMING_F4, { BIT_reg(5, m_registers.L()); })
Z80_OPCODE(6E, true, "BIT 5, (HL)", TIMING_F4, { BIT_addr(5, m_registers.HL.w); })
Z80_OPCODE(6F, true, "BIT 5, A", TIMING_F4, { BIT_reg(5, m_registers.A()); })
Z80_OPCODE(70, true, "BIT 6, B", TIMING_F4, { BIT_reg(6, m_registers.B()); })
Z80_OPCODE(71, true, "BIT 6, C", TIMING_F4, { BIT_reg(6, m_registers.C()); })
Z80_OPCODE(72, true, "BIT 6, D", TIMING_F4, { BIT_reg(6, m_registers.D()); })
Z80_OPCODE(73, true, "BIT 6, E", TIMING_F4, { BIT_reg(6, m_registers.E()); })
Z80_OPCODE(74, true, "BIT 6, H", TIMING_F4, { BIT_reg(6, m_registers.H()); })
Z80_OPCODE(75, true, "BIT 6, L", TIMING_F4, { BIT_reg(6, m_registers.L()); })
Z80_OPCODE(76, true, "BIT 6, (HL)", TIMING_F4, { BIT_addr(6, m_registers.HL.w); })
Z80_OPCODE(77, true, "BIT 6, A", TIMING_F4, { BIT_reg(6, m_registers.A()); })
Z80_OPCODE(78, true, "BIT 7, B", TIMING_F4, { BIT_reg(7, m_registers.B()); })
Z80_OPCODE(79, true, "BIT 7, C", TIMING_F4, { BIT_reg(7, m_registers.C()); })
Z80_OPCODE(7A, true, "BIT 7, D", TIMING_F4, { BIT_reg(7, m_registers.D()); })
Z80_OPCODE(7B, true, "BIT 7, E", TIMING_F4, { BIT_reg(7, m_registers.E()); })
Z80_OPCODE(7C, true, "BIT 7, H", TIMING_F4, { BIT_reg(7, m_registers.H()); })
Z80_OPCODE(7D, true, "BIT 7, L", TIMING_F4, { BIT_reg(7, m_registers.L()); })
Z80_OPCODE(7E, true, "BIT 7, (HL)", TIMING_F4, { BIT_addr(7, m_registers.HL.w); })
Z80_OPCODE(7F, true, "BIT 7, A", TIMING_F4, { BIT_reg(7, m_registers.A()); })
Z80_OPCODE(80, true, "RES 0, B", TIMING_F4, { RES_reg(0, &m_registers.B()); })
Z80_OPCODE(81, true, "RES 0, C", TIMING_F4, { RES_reg(0, &m_registers.C()); })
Z80_OPCODE(82, true, "RES 0, D", TIMING_F4, { RES_reg(0, &m_registers.D()); })
Z80_OPCODE(83, true, "RES 0, E", TIMING_F4, { RES_reg(0, &m_registers.E()); })
Z80_OPCODE(84, true, "RES 0, H", TIMING_F4, { RES_reg(0, &m_registers.H()); })
Z80_OPCODE(85, true, "RES 0, L", TIMING_F4, { RES_reg(0, &m_registers.L()); })
Z80_OPCODE(86, true, "RES 0, (HL)", TIMING_F4, { RES_addr(0, m_registers.HL.w); })
Z80_OPCODE(87, true, "RES 0, A", TIMING_F4, { RES_reg(0, &m_registers.A()); })
Z80_OPCODE(88, true, "RES 1, B", TIMING_F4, { RES_reg(1, &m_registers.B()); })
Z80_OPCODE(89, true, "RES 1, C", TIMING_F4, { RES_reg(1, &m_registers.C()); })
Z80_OPCODE(8A, true, "RES 1, D", TIMING_F4, { RES_reg(1, &m_registers.D()); })
Z80_OPCODE(8B, true, "RES 1, E", TIMING_F4, { RES_reg(1, &m_registers.E()); })
Z80_OPCODE(8C, true, "RES 1, H", TIMING_F4, { RES_reg(1, &m_registers.H()); })
Z80_OPCODE(8D, true, "RES 1, L", TIMING_F4, { RES_reg(1, &m_registers.L()); })
Z80_OPCODE(8E, true, "RES 1, (HL)", TIMING_F4, { RES_addr(1, m_registers.HL.w); })
Z80_OPCODE(8F, true, "RES 1, A", TIMING_F4, { RES_reg(1, &m_registers.A()); })
Z80_OPCODE(90, true, "RES 2, B", TIMING_F4, { RES_reg(2, &m_registers.B()); })
Z80_OPCODE(91, true, "RES 2, C", TIMING_F4, { RES_reg(2, &m_registers.C()); })
Z80_OPCODE(92, true, "RES 2, D", TIMING_F4, { RES_reg(2, &m_registers.D()); })
Z80_OPCODE(93, true, "RES 2, E", TIMING_F4, { RES_reg(2, &m_registers.E()); })
Z80_OPCODE(94, true, "RES 2, H", TIMING_F4, { RES_reg(2, &m_registers.H()); })
Z80_OPCODE(95, true, "RES 2, L", TIMING_F4, { RES_reg(2, &m_registers.L()); })
Z80_OPCODE(96, true, "RES 2, (HL)", TIMING_F4, { RES_addr(2, m_registers.HL.w); })
Z80_OPCODE(97, true, "RES 2, A", TIMING_F4, { RES_reg(2, &m_registers.A()); })
Z80_OPCODE(98, true, "RES 3, B", TIMING_F4, { RES_reg(3, &m_registers.B()); })
Z80_OPCODE(99, true, "RES 3, C", TIMING_F4, { RES_reg(3, &m_registers.C()); })
Z80_OPCODE(9A, true, "RES 3, D", TIMING_F4, { RES_reg(3, &m_registers.D()); })
Z80_OPCODE(9B, true, "RES 3, E", TIMING_F4, { RES_reg(3, &m_registers.E()); })
Z80_OPCODE(9C, true, "RES 3, H", TIMING_F4, { RES_reg(3, &m_registers.H()); })
Z80_OPCODE(9D, true, "RES 3, L", TIMING_F4, { RES_reg(3, &m_registers.L()); })
Z80_OPCODE(9E, true, "RES 3, (HL)", TIMING_F4, { RES_addr(3, m_registers.HL.w); })
Z80_OPCODE(9F, true, "RES 3, A", TIMING_F4, { RES_reg(3, &m_registers.A()); })
Z80_OPCODE(A0, true, "RES 4, B", TIMING_F4, { RES_reg(4, &m_registers.B()); })
Z80_OPCODE(A1, true, "RES 4, C", TIMING_F4, { RES_reg(4, &m_registers.C()); })
Z80_OPCODE(A2, true, "RES 4, D", TIMING_F4, { RES_reg(4, &m_registers.D()); })
Z80_OPCODE(A3, true, "RES 4, E", TIMING_F4, { RES_reg(4, &m_registers.E()); })
Z80_OPCODE(A4, true, "RES 4, H", TIMING_F4, { RES_reg(4, &m_registers.H()); })
Z80_OPCODE(A5, true, "RES 4, L", TIMING_F4, { RES_reg(4, &m_registers.L()); })
Z80_OPCODE(A6, true, "RES 4, (HL)", TIMING_F4, { RES_addr(4, m_registers.HL.w); })
Z80_OPCODE(A7, true, "RES 4, A", TIMING_F4, { RES_reg(4, &m_registers.A()); })
Z80_OPCODE(A8, true, "RES 5, B", TIMING_F4, { RES_reg(5, &m_registers.B()); })
Z80_OPCODE(A9, true, "RES 5, C", TIMING_F4, { RES_reg(5, &m_registers.C()); })
Z80_OPCODE(AA, true, "RES 5, D", TIMING_F4, { RES_reg(5, &m_registers.D()); })
Z80_OPCODE(AB, true, "RES 5, E", TIMING_F4, { RES_reg(5, &m_registers.E()); })
Z80_OPCODE(AC, true, "RES 5, H", TIMING_F4, { RES_reg(5, &m_registers.H()); })
Z80_OPCODE(AD, true, "RES 5, L", TIMING_F4, { RES_reg(5, &m_registers.L()); })
Z80_OPCODE(AE, true, "RES 5, (HL)", TIMING_F4, { RES_addr(5, m_registers.HL.w); })
Z80_OPCODE(AF, true, "RES 5, A", TIMING_F4, { RES_reg(5, &m_registers.A()); })
Z80_OPCODE(B0, true, "RES 6, B", TIMING_F4, { RES_reg(6, &m_registers.B()); })
Z80_OPCODE(B1, true, "RES 6, C", TIMING_F4, { RES_reg(6, &m_registers.C()); })
Z80_OPCODE(B2, true, "RES 6, D", TIMING_F4, { RES_reg(6, &m_registers.D()); })
Z80_OPCODE(B3, true, "RES 6, E", TIMING_F4, { RES_reg(6, &m_registers.E()); })
Z80_OPCODE(B4, true, "RES 6, H", TIMING_F4, { RES_reg(6, &m_registers.H()); })
Z80_OPCODE(B5, true, "RES 6, L", TIMING_F4, { RES_reg(6, &m_registers.L()); })
Z80_OPCODE(B6, true, "RES 6, (HL)", TIMING_F4, { RES_addr(6, m_registers.HL.w); })
Z80_OPCODE(B7, true, "RES 6, A", TIMING_F4, { RES_reg(6, &m_registers.A()); })
Z80_OPCODE(B8, true, "RES 7, B", TIMING_F4, { RES_reg(7, &m_registers.B()); })
Z80_OPCODE(B9, true, "RES 7, C", TIMING_F4, { RES_reg(7, &m_registers.C()); })
Z80_OPCODE(BA, true, "RES 7, D", TIMING_F4, { RES_reg(7, &m_registers.D()); })
Z80_OPCODE(BB, true, "RES 7, E", TIMING_F4, { RES_reg(7, &m_registers.E()); })
Z80_OPCODE(BC, true, "RES 7, H", TIMING_F4, { RES_reg(7, &m_registers.H()); })
Z80_OPCODE(BD, true, "RES 7, L", TIMING_F4, { RES_reg(7, &m_registers.L()); })
Z80_OPCODE(BE, true, "RES 7, (HL)", TIMING_F4, { RES_addr(7, m_registers.HL.w); })
Z80_OPCODE(BF, true, "RES 7, A", TIMING_F4, { RES_reg(7, &m_registers.A()); })
Z80_OPCODE(C0, true, "SET 0, B", TIMING_F4, { SET_reg(0, &m_registers.B()); })
Z80_OPCODE(C1, true, "SET 0, C", TIMING_F4, { SET_reg(0, &m_registers.C()); })
Z80_OPCODE(C2, true, "SET 0, D", TIMING_F4, { SET_reg(0, &m_registers.D()); })
Z80_OPCODE(C3, true, "SET 0, E", TIMING_F4, { SET_reg(0, &m_registers.E()); })
Z80_OPCODE(C4, true, "SET 0, H", TIMING_F4, { SET_reg(0, &m_registers.H()); })
Z80_OPCODE(C5, true, "SET 0, L", TIMING_F4, { SET_reg(0, &m_registers.L()); })
Z80_OPCODE(C6, true, "SET 0, (HL)", TIMING_F4, { SET_addr(0, m_registers.HL.w); })
Z80_OPCODE(C7, true, "SET 0, A", TIMING_F4, { SET_reg(0, &m_registers.A()); })
Z80_OPCODE(C8, true, "SET 1, B", TIMING_F4, { SET_reg(1, &m_registers.B()); })
Z80_OPCODE(C9, true, "SET 1, C", TIMING_F4, { SET_reg(1, &m_registers.C()); })
Z80_OPCODE(CA, true, "SET 1, D", TIMING_F4, { SET_reg(1, &m_registers.D()); })
Z80_OPCODE(CB, true, "SET 1, E", TIMING_F4, { SET_reg(1, &m_registers.E()); })
Z80_OPCODE(CC, true, "SET 1, H", TIMING_F4, { SET_reg(1, &m_registers.H()); })
Z80_OPCODE(CD, true, "SET 1, L", TIMING_F4, { SET_reg(1, &m_registers.L()); })
Z80_OPCODE(CE, true, "SET 1, (HL)", TIMING_F4, { SET_addr(1, m_registers.HL.w); })
Z80_OPCODE(CF, true, "SET 1, A", TIMING_F4, { SET_reg(1, &m_registers.A()); })
Z80_OPCODE(D0, true, "SET 2, B", TIMING_F4, { SET_reg(2, &m_registers.B()); })
Z80_OPCODE(D1, true, "SET 2, C", TIMING_F4, { SET_reg(2, &m_registers.C()); })
Z80_OPCODE(D2, true, "SET 2, D", TIMING_F4, { SET_reg(2, &m_registers.D()); })
Z80_OPCODE(D3, true, "SET 2, E", TIMING_F4, { SET_reg(2, &m_registers.E()); })
Z80_OPCODE(D4, true, "SET 2, H", TIMING_F4, { SET_reg(2, &m_registers.H()); })
Z80_OPCODE(D5, true, "SET 2, L", TIMING_F4, { SET_reg(2, &m_registers.L()); })
Z80_OPCODE(D6, true, "SET 2, (HL)", TIMING_F4, { SET_addr(2, m_registers.HL.w); })
Z80_OPCODE(D7, true, "SET 2, A", TIMING_F4, { SET_reg(2, &m_registers.A()); })
Z80_OPCODE(D8, true, "SET 3, B", TIMING_F4, { SET_reg(3, &m_registers.B()); })
Z80_OPCODE(D9, true, "SET 3, C", TIMING_F4, { SET_reg(3, &m_registers.C()); })
Z80_OPCODE(DA, true, "SET 3, D", TIMING_F4, { SET_reg(3, &m_registers.D()); })
Z80_OPCODE(DB, true, "SET 3, E", TIMING_F4, { SET_reg(3, &m_registers.E()); })
Z80_OPCODE(DC, true, "SET 3, H", TIMING_F4, { SET_reg(3, &m_registers.H()); })
Z80_OPCODE(DD, true, "SET 3, L", TIMING_F4, { SET_reg(3, &m_registers.L()); })
Z80_OPCODE(DE, true, "SET 3, (HL)", TIMING_F4, { SET_addr(3, m_registers.HL.w); })
Z80_OPCODE(DF, true, "SET 3, A", TIMING_F4, { SET_reg(3, &m_registers.A()); })
Z80_OPCODE(E0, true, "SET 4, B", TIMING_F4, { SET_reg(4, &m_registers.B()); })
Z80_OPCODE(E1, true, "SET 4, C", TIMING_F4, { SET_reg(4, &m_registers.C()); })
Z80_OPCODE(E2, true, "SET 4, D", TIMING_F4, { SET_reg(4, &m_registers.D()); })
Z80_OPCODE(E3, true, "SET 4, E", TIMING_F4, { SET_reg(4, &m_registers.E()); })
Z80_OPCODE(E4, true, "SET 4, H", TIMING_F4, { SET_reg(4, &m_registers.H()); })
Z80_OPCODE(E5, true, "SET 4, L", TIMING_F4, { SET_reg(4, &m_registers.L()); })
Z80_OPCODE(E6, true, "SET 4, (HL)", TIMING_F4, { SET_addr(4, m_registers.HL.w); })
Z80_OPCODE(E7, true, "SET 4, A", TIMING_F4, { SET_reg(4, &m_registers.A()); })
Z80_OPCODE(E8, true, "SET 5, B", TIMING_F4, { SET_reg(5, &m_registers.B()); })
Z80_OPCODE(E9, true, "SET 5, C", TIMING_F4, { SET_reg(5, &m_registers.C()); })
Z80_OPCODE(EA, true, "SET 5, D", TIMING_F4, { SET_reg(5, &m_registers.D()); })
Z80_OPCODE(EB, true, "SET 5, E", TIMING_F4, { SET_reg(5, &m_registers.E()); })
Z80_OPCODE(EC, true, "SET 5, H", TIMING_F4, { SET_reg(5, &m_registers.H()); })
Z80_OPCODE(ED, true, "SET 5, L", TIMING_F4, { SET_reg(5, &m_registers.L()); })
Z80_OPCODE(EE, true, "SET 5, (HL)", TIMING_F4, { SET_addr(5, m_registers.HL.w); })
Z80_OPCODE(EF, true, "SET 5, A", TIMING_F4, { SET_reg(5, &m_registers.A()); })
Z80_OPCODE(F0, true, "SET 6, B", TIMING_F4, { SET_reg(6, &m_registers.B()); })
Z80_OPCODE(F1, true, "SET 6, C", TIMING_F4, { SET_reg(6, &m_registers.C()); })
Z80_OPCODE(F2, true, "SET 6, D", TIMING_F4, { SET_reg(6, &m_registers.D()); })
Z80_OPCODE(F3, true, "SET 6, E", TIMING_F4, { SET_reg(6, &m_registers.E()); })
Z80_OPCODE(F4, true, "SET 6, H", TIMING_F4, { SET_reg(6, &m_registers.H()); })
Z80_OPCODE(F5, true, "SET 6, L", TIMING_F4, { SET_reg(6, &m_registers.L()); })
Z80_OPCODE(F6, true, "SET 6, (HL)", TIMING_F4, { SET_addr(6, m_registers.HL.w); })
Z80_OPCODE(F7, true, "SET 6, A", TIMING_F4, { SET_reg(6, &m_registers.A()); })
Z80_OPCODE(F8, true, "SET 7, B", TIMING_F4, { SET_reg(7, &m_registers.B()); })
Z80_OPCODE(F9, true, "SET 7, C", TIMING_F4, { SET_reg(7, &m_registers.C()); })
Z80_OPCODE(FA, true, "SET 7, D", TIMING_F4, { SET_reg(7, &m_registers.D()); })
Z80_OPCODE(FB, true, "SET 7, E", TIMING_F4, { SET_reg(7, &m_registers.E()); })
Z80_OPCODE(FC, true, "SET 7, H", TIMING_F4, { SET_reg(7, &m_registers.H()); })
Z80_OPCODE(FD, true, "SET 7, L", TIMING_F4, { SET_reg(7, &m_registers.L()); })
Z80_OPCODE(FE, true, "SET 7, (HL)", TIMING_F4, { SET_addr(7, m_registers.HL.w); })
Z80_OPCODE(FF, true, "SET 7, A", TIMING_F4, { SET_reg(7, &m_registers.A()); })
