//------------------------------------------------------------------------------
// *** DO NOT INCLUDE DIRECTLY ***
//
// These macros generate code and populate several tables related to opcodes automatically.
//------------------------------------------------------------------------------

Z80_OPCODE(00, true, "RLC", "(IY + %n), B", TIMING_F4M3I5M4M3, { RLC_addrreg_offset_reg(m_registers.IY, &m_registers.B()); })
Z80_OPCODE(01, true, "RLC", "(IY + %n), C", TIMING_F4M3I5M4M3, { RLC_addrreg_offset_reg(m_registers.IY, &m_registers.C()); })
Z80_OPCODE(02, true, "RLC", "(IY + %n), D", TIMING_F4M3I5M4M3, { RLC_addrreg_offset_reg(m_registers.IY, &m_registers.D()); })
Z80_OPCODE(03, true, "RLC", "(IY + %n), E", TIMING_F4M3I5M4M3, { RLC_addrreg_offset_reg(m_registers.IY, &m_registers.E()); })
Z80_OPCODE(04, true, "RLC", "(IY + %n), H", TIMING_F4M3I5M4M3, { RLC_addrreg_offset_reg(m_registers.IY, &m_registers.H()); })
Z80_OPCODE(05, true, "RLC", "(IY + %n), L", TIMING_F4M3I5M4M3, { RLC_addrreg_offset_reg(m_registers.IY, &m_registers.L()); })
Z80_OPCODE(06, true, "RLC", "(IY + %n)", TIMING_F4M3I5M4M3, { RLC_addrreg_offset(m_registers.IY); })
Z80_OPCODE(07, true, "RLC", "(IY + %n), A", TIMING_F4M3I5M4M3, { RLC_addrreg_offset_reg(m_registers.IY, &m_registers.A()); })
Z80_OPCODE(08, true, "RRC", "(IY + %n), B", TIMING_F4M3I5M4M3, { RRC_addrreg_offset_reg(m_registers.IY, &m_registers.B()); })
Z80_OPCODE(09, true, "RRC", "(IY + %n), C", TIMING_F4M3I5M4M3, { RRC_addrreg_offset_reg(m_registers.IY, &m_registers.C()); })
Z80_OPCODE(0A, true, "RRC", "(IY + %n), D", TIMING_F4M3I5M4M3, { RRC_addrreg_offset_reg(m_registers.IY, &m_registers.D()); })
Z80_OPCODE(0B, true, "RRC", "(IY + %n), E", TIMING_F4M3I5M4M3, { RRC_addrreg_offset_reg(m_registers.IY, &m_registers.E()); })
Z80_OPCODE(0C, true, "RRC", "(IY + %n), H", TIMING_F4M3I5M4M3, { RRC_addrreg_offset_reg(m_registers.IY, &m_registers.H()); })
Z80_OPCODE(0D, true, "RRC", "(IY + %n), L", TIMING_F4M3I5M4M3, { RRC_addrreg_offset_reg(m_registers.IY, &m_registers.L()); })
Z80_OPCODE(0E, true, "RRC", "(IY + %n)", TIMING_F4M3I5M4M3, { RRC_addrreg_offset(m_registers.IY); })
Z80_OPCODE(0F, true, "RRC", "(IY + %n), A", TIMING_F4M3I5M4M3, { RRC_addrreg_offset_reg(m_registers.IY, &m_registers.A()); })
Z80_OPCODE(10, true, "RL", "(IY + %n), B", TIMING_F4M3I5M4M3, { RL_addrreg_offset_reg(m_registers.IY, &m_registers.B()); })
Z80_OPCODE(11, true, "RL", "(IY + %n), C", TIMING_F4M3I5M4M3, { RL_addrreg_offset_reg(m_registers.IY, &m_registers.C()); })
Z80_OPCODE(12, true, "RL", "(IY + %n), D", TIMING_F4M3I5M4M3, { RL_addrreg_offset_reg(m_registers.IY, &m_registers.D()); })
Z80_OPCODE(13, true, "RL", "(IY + %n), E", TIMING_F4M3I5M4M3, { RL_addrreg_offset_reg(m_registers.IY, &m_registers.E()); })
Z80_OPCODE(14, true, "RL", "(IY + %n), H", TIMING_F4M3I5M4M3, { RL_addrreg_offset_reg(m_registers.IY, &m_registers.H()); })
Z80_OPCODE(15, true, "RL", "(IY + %n), L", TIMING_F4M3I5M4M3, { RL_addrreg_offset_reg(m_registers.IY, &m_registers.L()); })
Z80_OPCODE(16, true, "RL", "(IY + %n)", TIMING_F4M3I5M4M3, { RL_addrreg_offset(m_registers.IY); })
Z80_OPCODE(17, true, "RL", "(IY + %n), A", TIMING_F4M3I5M4M3, { RL_addrreg_offset_reg(m_registers.IY, &m_registers.A()); })
Z80_OPCODE(18, true, "RR", "(IY + %n), B", TIMING_F4M3I5M4M3, { RR_addrreg_offset_reg(m_registers.IY, &m_registers.B()); })
Z80_OPCODE(19, true, "RR", "(IY + %n), C", TIMING_F4M3I5M4M3, { RR_addrreg_offset_reg(m_registers.IY, &m_registers.C()); })
Z80_OPCODE(1A, true, "RR", "(IY + %n), D", TIMING_F4M3I5M4M3, { RR_addrreg_offset_reg(m_registers.IY, &m_registers.D()); })
Z80_OPCODE(1B, true, "RR", "(IY + %n), E", TIMING_F4M3I5M4M3, { RR_addrreg_offset_reg(m_registers.IY, &m_registers.E()); })
Z80_OPCODE(1C, true, "RR", "(IY + %n), H", TIMING_F4M3I5M4M3, { RR_addrreg_offset_reg(m_registers.IY, &m_registers.H()); })
Z80_OPCODE(1D, true, "RR", "(IY + %n), L", TIMING_F4M3I5M4M3, { RR_addrreg_offset_reg(m_registers.IY, &m_registers.L()); })
Z80_OPCODE(1E, true, "RR", "(IY + %n)", TIMING_F4M3I5M4M3, { RR_addrreg_offset(m_registers.IY); })
Z80_OPCODE(1F, true, "RR", "(IY + %n), A", TIMING_F4M3I5M4M3, { RR_addrreg_offset_reg(m_registers.IY, &m_registers.A()); })
Z80_OPCODE(20, true, "SLA", "(IY + %n), B", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.B(), false); })
Z80_OPCODE(21, true, "SLA", "(IY + %n), C", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.C(), false); })
Z80_OPCODE(22, true, "SLA", "(IY + %n), D", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.D(), false); })
Z80_OPCODE(23, true, "SLA", "(IY + %n), E", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.E(), false); })
Z80_OPCODE(24, true, "SLA", "(IY + %n), H", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.H(), false); })
Z80_OPCODE(25, true, "SLA", "(IY + %n), L", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.L(), false); })
Z80_OPCODE(26, true, "SLA", "(IY + %n)", TIMING_F4M3I5M4M3, { SL_addrreg_offset(m_registers.IY, false); })
Z80_OPCODE(27, true, "SLA", "(IY + %n), A", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.A(), false); })
Z80_OPCODE(28, true, "SRA", "(IY + %n), B", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.B(), (m_registers.B() & 0x80) != 0); })
Z80_OPCODE(29, true, "SRA", "(IY + %n), C", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.C(), (m_registers.C() & 0x80) != 0); })
Z80_OPCODE(2A, true, "SRA", "(IY + %n), D", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.D(), (m_registers.D() & 0x80) != 0); })
Z80_OPCODE(2B, true, "SRA", "(IY + %n), E", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.E(), (m_registers.E() & 0x80) != 0); })
Z80_OPCODE(2C, true, "SRA", "(IY + %n), H", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.H(), (m_registers.H() & 0x80) != 0); })
Z80_OPCODE(2D, true, "SRA", "(IY + %n), L", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.L(), (m_registers.L() & 0x80) != 0); })
Z80_OPCODE(2E, true, "SRA", "(IY + %n)", TIMING_F4M3I5M4M3, { SRA_addrreg_offset(m_registers.IY); })
Z80_OPCODE(2F, true, "SRA", "(IY + %n), A", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.A(), (m_registers.A() & 0x80) != 0); })
Z80_OPCODE(30, true, "SLL", "(IY + %n), B", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.B(), true); })
Z80_OPCODE(31, true, "SLL", "(IY + %n), C", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.C(), true); })
Z80_OPCODE(32, true, "SLL", "(IY + %n), D", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.D(), true); })
Z80_OPCODE(33, true, "SLL", "(IY + %n), E", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.E(), true); })
Z80_OPCODE(34, true, "SLL", "(IY + %n), H", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.H(), true); })
Z80_OPCODE(35, true, "SLL", "(IY + %n), L", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.L(), true); })
Z80_OPCODE(36, true, "SLL", "(IY + %n)", TIMING_F4M3I5M4M3, { SL_addrreg_offset(m_registers.IY, true); })
Z80_OPCODE(37, true, "SLL", "(IY + %n), A", TIMING_F4M3I5M4M3, { SL_addrreg_offset_reg(m_registers.IY, &m_registers.A(), true); })
Z80_OPCODE(38, true, "SRL", "(IY + %n), B", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.B(), false); })
Z80_OPCODE(39, true, "SRL", "(IY + %n), C", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.C(), false); })
Z80_OPCODE(3A, true, "SRL", "(IY + %n), D", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.D(), false); })
Z80_OPCODE(3B, true, "SRL", "(IY + %n), E", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.E(), false); })
Z80_OPCODE(3C, true, "SRL", "(IY + %n), H", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.H(), false); })
Z80_OPCODE(3D, true, "SRL", "(IY + %n), L", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.L(), false); })
Z80_OPCODE(3E, true, "SRL", "(IY + %n)", TIMING_F4M3I5M4M3, { SRL_addrreg_offset(m_registers.IY); })
Z80_OPCODE(3F, true, "SRL", "(IY + %n), A", TIMING_F4M3I5M4M3, { SR_addrreg_offset_reg(m_registers.IY, &m_registers.A(), false); })
Z80_OPCODE(40, true, "BIT", "0, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(0, m_registers.IY.w); })
Z80_OPCODE(41, true, "BIT", "0, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(0, m_registers.IY.w); })
Z80_OPCODE(42, true, "BIT", "0, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(0, m_registers.IY.w); })
Z80_OPCODE(43, true, "BIT", "0, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(0, m_registers.IY.w); })
Z80_OPCODE(44, true, "BIT", "0, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(0, m_registers.IY.w); })
Z80_OPCODE(45, true, "BIT", "0, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(0, m_registers.IY.w); })
Z80_OPCODE(46, true, "BIT", "0, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(0, m_registers.IY.w); })
Z80_OPCODE(47, true, "BIT", "0, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(0, m_registers.IY.w); })
Z80_OPCODE(48, true, "BIT", "1, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(1, m_registers.IY.w); })
Z80_OPCODE(49, true, "BIT", "1, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(1, m_registers.IY.w); })
Z80_OPCODE(4A, true, "BIT", "1, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(1, m_registers.IY.w); })
Z80_OPCODE(4B, true, "BIT", "1, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(1, m_registers.IY.w); })
Z80_OPCODE(4C, true, "BIT", "1, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(1, m_registers.IY.w); })
Z80_OPCODE(4D, true, "BIT", "1, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(1, m_registers.IY.w); })
Z80_OPCODE(4E, true, "BIT", "1, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(1, m_registers.IY.w); })
Z80_OPCODE(4F, true, "BIT", "1, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(1, m_registers.IY.w); })
Z80_OPCODE(50, true, "BIT", "2, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(2, m_registers.IY.w); })
Z80_OPCODE(51, true, "BIT", "2, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(2, m_registers.IY.w); })
Z80_OPCODE(52, true, "BIT", "2, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(2, m_registers.IY.w); })
Z80_OPCODE(53, true, "BIT", "2, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(2, m_registers.IY.w); })
Z80_OPCODE(54, true, "BIT", "2, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(2, m_registers.IY.w); })
Z80_OPCODE(55, true, "BIT", "2, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(2, m_registers.IY.w); })
Z80_OPCODE(56, true, "BIT", "2, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(2, m_registers.IY.w); })
Z80_OPCODE(57, true, "BIT", "2, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(2, m_registers.IY.w); })
Z80_OPCODE(58, true, "BIT", "3, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(3, m_registers.IY.w); })
Z80_OPCODE(59, true, "BIT", "3, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(3, m_registers.IY.w); })
Z80_OPCODE(5A, true, "BIT", "3, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(3, m_registers.IY.w); })
Z80_OPCODE(5B, true, "BIT", "3, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(3, m_registers.IY.w); })
Z80_OPCODE(5C, true, "BIT", "3, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(3, m_registers.IY.w); })
Z80_OPCODE(5D, true, "BIT", "3, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(3, m_registers.IY.w); })
Z80_OPCODE(5E, true, "BIT", "3, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(3, m_registers.IY.w); })
Z80_OPCODE(5F, true, "BIT", "3, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(3, m_registers.IY.w); })
Z80_OPCODE(60, true, "BIT", "4, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(4, m_registers.IY.w); })
Z80_OPCODE(61, true, "BIT", "4, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(4, m_registers.IY.w); })
Z80_OPCODE(62, true, "BIT", "4, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(4, m_registers.IY.w); })
Z80_OPCODE(63, true, "BIT", "4, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(4, m_registers.IY.w); })
Z80_OPCODE(64, true, "BIT", "4, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(4, m_registers.IY.w); })
Z80_OPCODE(65, true, "BIT", "4, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(4, m_registers.IY.w); })
Z80_OPCODE(66, true, "BIT", "4, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(4, m_registers.IY.w); })
Z80_OPCODE(67, true, "BIT", "4, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(4, m_registers.IY.w); })
Z80_OPCODE(68, true, "BIT", "5, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(5, m_registers.IY.w); })
Z80_OPCODE(69, true, "BIT", "5, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(5, m_registers.IY.w); })
Z80_OPCODE(6A, true, "BIT", "5, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(5, m_registers.IY.w); })
Z80_OPCODE(6B, true, "BIT", "5, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(5, m_registers.IY.w); })
Z80_OPCODE(6C, true, "BIT", "5, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(5, m_registers.IY.w); })
Z80_OPCODE(6D, true, "BIT", "5, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(5, m_registers.IY.w); })
Z80_OPCODE(6E, true, "BIT", "5, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(5, m_registers.IY.w); })
Z80_OPCODE(6F, true, "BIT", "5, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(5, m_registers.IY.w); })
Z80_OPCODE(70, true, "BIT", "6, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(6, m_registers.IY.w); })
Z80_OPCODE(71, true, "BIT", "6, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(6, m_registers.IY.w); })
Z80_OPCODE(72, true, "BIT", "6, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(6, m_registers.IY.w); })
Z80_OPCODE(73, true, "BIT", "6, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(6, m_registers.IY.w); })
Z80_OPCODE(74, true, "BIT", "6, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(6, m_registers.IY.w); })
Z80_OPCODE(75, true, "BIT", "6, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(6, m_registers.IY.w); })
Z80_OPCODE(76, true, "BIT", "6, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(6, m_registers.IY.w); })
Z80_OPCODE(77, true, "BIT", "6, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(6, m_registers.IY.w); })
Z80_OPCODE(78, true, "BIT", "7, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(7, m_registers.IY.w); })
Z80_OPCODE(79, true, "BIT", "7, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(7, m_registers.IY.w); })
Z80_OPCODE(7A, true, "BIT", "7, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(7, m_registers.IY.w); })
Z80_OPCODE(7B, true, "BIT", "7, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(7, m_registers.IY.w); })
Z80_OPCODE(7C, true, "BIT", "7, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(7, m_registers.IY.w); })
Z80_OPCODE(7D, true, "BIT", "7, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(7, m_registers.IY.w); })
Z80_OPCODE(7E, true, "BIT", "7, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(7, m_registers.IY.w); })
Z80_OPCODE(7F, true, "BIT", "7, (IY + %n)", TIMING_F4M3I5M4, { BIT_addr_offset(7, m_registers.IY.w); })
Z80_OPCODE(80, true, "RES", "0, (IY + %n), B", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(0, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(81, true, "RES", "0, (IY + %n), C", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(0, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(82, true, "RES", "0, (IY + %n), D", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(0, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(83, true, "RES", "0, (IY + %n), E", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(0, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(84, true, "RES", "0, (IY + %n), H", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(0, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(85, true, "RES", "0, (IY + %n), L", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(0, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(86, true, "RES", "0, (IY + %n)",    TIMING_F4M3I5M4M3, { RES_addr_offset(0, m_registers.IY.w); })
Z80_OPCODE(87, true, "RES", "0, (IY + %n), A", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(0, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(88, true, "RES", "1, (IY + %n), B", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(1, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(89, true, "RES", "1, (IY + %n), C", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(1, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(8A, true, "RES", "1, (IY + %n), D", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(1, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(8B, true, "RES", "1, (IY + %n), E", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(1, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(8C, true, "RES", "1, (IY + %n), H", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(1, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(8D, true, "RES", "1, (IY + %n), L", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(1, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(8E, true, "RES", "1, (IY + %n)",    TIMING_F4M3I5M4M3, { RES_addr_offset(1, m_registers.IY.w); })
Z80_OPCODE(8F, true, "RES", "1, (IY + %n), A", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(1, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(90, true, "RES", "2, (IY + %n), B", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(2, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(91, true, "RES", "2, (IY + %n), C", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(2, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(92, true, "RES", "2, (IY + %n), D", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(2, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(93, true, "RES", "2, (IY + %n), E", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(2, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(94, true, "RES", "2, (IY + %n), H", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(2, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(95, true, "RES", "2, (IY + %n), L", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(2, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(96, true, "RES", "2, (IY + %n)",    TIMING_F4M3I5M4M3, { RES_addr_offset(2, m_registers.IY.w); })
Z80_OPCODE(97, true, "RES", "2, (IY + %n), A", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(2, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(98, true, "RES", "3, (IY + %n), B", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(3, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(99, true, "RES", "3, (IY + %n), C", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(3, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(9A, true, "RES", "3, (IY + %n), D", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(3, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(9B, true, "RES", "3, (IY + %n), E", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(3, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(9C, true, "RES", "3, (IY + %n), H", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(3, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(9D, true, "RES", "3, (IY + %n), L", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(3, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(9E, true, "RES", "3, (IY + %n)",    TIMING_F4M3I5M4M3, { RES_addr_offset(3, m_registers.IY.w); })
Z80_OPCODE(9F, true, "RES", "3, (IY + %n), A", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(3, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(A0, true, "RES", "4, (IY + %n), B", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(4, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(A1, true, "RES", "4, (IY + %n), C", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(4, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(A2, true, "RES", "4, (IY + %n), D", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(4, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(A3, true, "RES", "4, (IY + %n), E", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(4, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(A4, true, "RES", "4, (IY + %n), H", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(4, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(A5, true, "RES", "4, (IY + %n), L", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(4, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(A6, true, "RES", "4, (IY + %n)",    TIMING_F4M3I5M4M3, { RES_addr_offset(4, m_registers.IY.w); })
Z80_OPCODE(A7, true, "RES", "4, (IY + %n), A", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(4, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(A8, true, "RES", "5, (IY + %n), B", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(5, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(A9, true, "RES", "5, (IY + %n), C", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(5, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(AA, true, "RES", "5, (IY + %n), D", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(5, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(AB, true, "RES", "5, (IY + %n), E", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(5, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(AC, true, "RES", "5, (IY + %n), H", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(5, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(AD, true, "RES", "5, (IY + %n), L", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(5, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(AE, true, "RES", "5, (IY + %n)",    TIMING_F4M3I5M4M3, { RES_addr_offset(5, m_registers.IY.w); })
Z80_OPCODE(AF, true, "RES", "5, (IY + %n), A", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(5, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(B0, true, "RES", "6, (IY + %n), B", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(6, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(B1, true, "RES", "6, (IY + %n), C", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(6, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(B2, true, "RES", "6, (IY + %n), D", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(6, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(B3, true, "RES", "6, (IY + %n), E", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(6, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(B4, true, "RES", "6, (IY + %n), H", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(6, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(B5, true, "RES", "6, (IY + %n), L", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(6, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(B6, true, "RES", "6, (IY + %n)",    TIMING_F4M3I5M4M3, { RES_addr_offset(6, m_registers.IY.w); })
Z80_OPCODE(B7, true, "RES", "6, (IY + %n), A", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(6, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(B8, true, "RES", "7, (IY + %n), B", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(7, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(B9, true, "RES", "7, (IY + %n), C", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(7, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(BA, true, "RES", "7, (IY + %n), D", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(7, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(BB, true, "RES", "7, (IY + %n), E", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(7, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(BC, true, "RES", "7, (IY + %n), H", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(7, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(BD, true, "RES", "7, (IY + %n), L", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(7, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(BE, true, "RES", "7, (IY + %n)",    TIMING_F4M3I5M4M3, { RES_addr_offset(7, m_registers.IY.w); })
Z80_OPCODE(BF, true, "RES", "7, (IY + %n), A", TIMING_F4M3I5M4M3, { RES_addr_offset_reg(7, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(C0, true, "SET", "0, (IY + %n), B", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(0, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(C1, true, "SET", "0, (IY + %n), C", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(0, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(C2, true, "SET", "0, (IY + %n), D", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(0, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(C3, true, "SET", "0, (IY + %n), E", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(0, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(C4, true, "SET", "0, (IY + %n), H", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(0, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(C5, true, "SET", "0, (IY + %n), L", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(0, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(C6, true, "SET", "0, (IY + %n)",    TIMING_F4M3I5M4M3, { SET_addr_offset(0, m_registers.IY.w); })
Z80_OPCODE(C7, true, "SET", "0, (IY + %n), A", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(0, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(C8, true, "SET", "1, (IY + %n), B", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(1, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(C9, true, "SET", "1, (IY + %n), C", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(1, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(CA, true, "SET", "1, (IY + %n), D", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(1, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(CB, true, "SET", "1, (IY + %n), E", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(1, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(CC, true, "SET", "1, (IY + %n), H", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(1, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(CD, true, "SET", "1, (IY + %n), L", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(1, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(CE, true, "SET", "1, (IY + %n)",    TIMING_F4M3I5M4M3, { SET_addr_offset(1, m_registers.IY.w); })
Z80_OPCODE(CF, true, "SET", "1, (IY + %n), A", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(1, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(D0, true, "SET", "2, (IY + %n), B", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(2, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(D1, true, "SET", "2, (IY + %n), C", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(2, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(D2, true, "SET", "2, (IY + %n), D", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(2, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(D3, true, "SET", "2, (IY + %n), E", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(2, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(D4, true, "SET", "2, (IY + %n), H", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(2, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(D5, true, "SET", "2, (IY + %n), L", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(2, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(D6, true, "SET", "2, (IY + %n)",    TIMING_F4M3I5M4M3, { SET_addr_offset(2, m_registers.IY.w); })
Z80_OPCODE(D7, true, "SET", "2, (IY + %n), A", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(2, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(D8, true, "SET", "3, (IY + %n), B", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(3, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(D9, true, "SET", "3, (IY + %n), C", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(3, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(DA, true, "SET", "3, (IY + %n), D", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(3, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(DB, true, "SET", "3, (IY + %n), E", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(3, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(DC, true, "SET", "3, (IY + %n), H", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(3, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(DD, true, "SET", "3, (IY + %n), L", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(3, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(DE, true, "SET", "3, (IY + %n)",    TIMING_F4M3I5M4M3, { SET_addr_offset(3, m_registers.IY.w); })
Z80_OPCODE(DF, true, "SET", "3, (IY + %n), A", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(3, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(E0, true, "SET", "4, (IY + %n), B", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(4, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(E1, true, "SET", "4, (IY + %n), C", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(4, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(E2, true, "SET", "4, (IY + %n), D", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(4, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(E3, true, "SET", "4, (IY + %n), E", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(4, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(E4, true, "SET", "4, (IY + %n), H", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(4, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(E5, true, "SET", "4, (IY + %n), L", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(4, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(E6, true, "SET", "4, (IY + %n)",    TIMING_F4M3I5M4M3, { SET_addr_offset(4, m_registers.IY.w); })
Z80_OPCODE(E7, true, "SET", "4, (IY + %n), A", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(4, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(E8, true, "SET", "5, (IY + %n), B", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(5, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(E9, true, "SET", "5, (IY + %n), C", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(5, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(EA, true, "SET", "5, (IY + %n), D", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(5, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(EB, true, "SET", "5, (IY + %n), E", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(5, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(EC, true, "SET", "5, (IY + %n), H", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(5, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(ED, true, "SET", "5, (IY + %n), L", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(5, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(EE, true, "SET", "5, (IY + %n)",    TIMING_F4M3I5M4M3, { SET_addr_offset(5, m_registers.IY.w); })
Z80_OPCODE(EF, true, "SET", "5, (IY + %n), A", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(5, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(F0, true, "SET", "6, (IY + %n), B", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(6, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(F1, true, "SET", "6, (IY + %n), C", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(6, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(F2, true, "SET", "6, (IY + %n), D", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(6, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(F3, true, "SET", "6, (IY + %n), E", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(6, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(F4, true, "SET", "6, (IY + %n), H", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(6, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(F5, true, "SET", "6, (IY + %n), L", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(6, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(F6, true, "SET", "6, (IY + %n)",    TIMING_F4M3I5M4M3, { SET_addr_offset(6, m_registers.IY.w); })
Z80_OPCODE(F7, true, "SET", "6, (IY + %n), A", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(6, m_registers.IY.w, &m_registers.A()); })
Z80_OPCODE(F8, true, "SET", "7, (IY + %n), B", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(7, m_registers.IY.w, &m_registers.B()); })
Z80_OPCODE(F9, true, "SET", "7, (IY + %n), C", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(7, m_registers.IY.w, &m_registers.C()); })
Z80_OPCODE(FA, true, "SET", "7, (IY + %n), D", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(7, m_registers.IY.w, &m_registers.D()); })
Z80_OPCODE(FB, true, "SET", "7, (IY + %n), E", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(7, m_registers.IY.w, &m_registers.E()); })
Z80_OPCODE(FC, true, "SET", "7, (IY + %n), H", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(7, m_registers.IY.w, &m_registers.H()); })
Z80_OPCODE(FD, true, "SET", "7, (IY + %n), L", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(7, m_registers.IY.w, &m_registers.L()); })
Z80_OPCODE(FE, true, "SET", "7, (IY + %n)",    TIMING_F4M3I5M4M3, { SET_addr_offset(7, m_registers.IY.w); })
Z80_OPCODE(FF, true, "SET", "7, (IY + %n), A", TIMING_F4M3I5M4M3, { SET_addr_offset_reg(7, m_registers.IY.w, &m_registers.A()); })
