//------------------------------------------------------------------------------
// *** DO NOT INCLUDE DIRECTLY ***
//
// These macros generate code and populate several tables related to opcodes automatically.
//------------------------------------------------------------------------------

Z80_OPCODE(00, true, "NOP", { /* Do nothing. */ })
Z80_OPCODE(01, true, "LD BC, %nn", { LD16_reg_nn(&m_registers.BC); })
Z80_OPCODE(02, true, "LD (BC), A", { LD8_addrreg_valuereg(m_registers.BC, m_registers.A()); })
Z80_OPCODE(03, true, "INC BC", { INC16_reg(&m_registers.BC); })
Z80_OPCODE(04, true, "INC B", { INC8_reg(&m_registers.B()); })
Z80_OPCODE(05, true, "DEC B", { DEC8_reg(&m_registers.B()); })
Z80_OPCODE(06, true, "LD B, %n", { LD8_reg_n(&m_registers.B()); })
Z80_OPCODE(07, true, "RLCA", { RLC(&m_registers.A()); })
Z80_OPCODE(08, true, "EX AF, AF'", { EX_reg_reg(&m_registers.AF, &m_registers.altAF); })
Z80_OPCODE(09, true, "ADD HL, BC", { ADD16_reg_reg(&m_registers.HL, m_registers.BC); })
Z80_OPCODE(0A, true, "LD A,(BC)", { LD8_reg_mem(&m_registers.A(), m_registers.BC); })
Z80_OPCODE(0B, true, "DEC BC", { DEC16_reg(&m_registers.BC); })
Z80_OPCODE(0C, true, "INC C", { INC8_reg(&m_registers.C()); })
Z80_OPCODE(0D, true, "DEC C", { DEC8_reg(&m_registers.C()); })
Z80_OPCODE(0E, true, "LD C, %n", { LD8_reg_n(&m_registers.C()); })
Z80_OPCODE(0F, true, "RRCA", { RRC(&m_registers.A()); })
Z80_OPCODE(10, true, "DJNZ %n", { DJNZ_n(); })
Z80_OPCODE(11, true, "LD DE, %nn", { LD16_reg_nn(&m_registers.DE); })
Z80_OPCODE(12, true, "LD (DE), A", { LD8_addrreg_valuereg(m_registers.DE, m_registers.A()); })
Z80_OPCODE(13, true, "INC DE", { INC16_reg(&m_registers.DE); })
Z80_OPCODE(14, true, "INC D", { INC8_reg(&m_registers.D()); })
Z80_OPCODE(15, true, "DEC D", { DEC8_reg(&m_registers.D()); })
Z80_OPCODE(16, true, "LD D, %n", { LD8_reg_n(&m_registers.D()); })
Z80_OPCODE(17, true, "RLA", { RL(&m_registers.A()); })
Z80_OPCODE(18, true, "JR %n", { JR_n(); })
Z80_OPCODE(19, true, "ADD HL, DE", { ADD16_reg_reg(&m_registers.HL, m_registers.DE); })
Z80_OPCODE(1A, true, "LD A, (DE)", { LD8_reg_mem(&m_registers.A(), m_registers.DE); })
Z80_OPCODE(1B, true, "DEC DE", { DEC16_reg(&m_registers.DE); })
Z80_OPCODE(1C, true, "INC E", { INC8_reg(&m_registers.E()); })
Z80_OPCODE(1D, true, "DEC E", { DEC8_reg(&m_registers.E()); })
Z80_OPCODE(1E, true, "LD E, %n", { LD8_reg_n(&m_registers.E()); })
Z80_OPCODE(1F, true, "RRA", { RR(&m_registers.A()); })
Z80_OPCODE(20, true, "JR NZ, %n", { JR_condition_n(!m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(21, true, "LD HL, %nn", { LD16_reg_nn(&m_registers.HL); })
Z80_OPCODE(22, true, "LD (%nn), HL", { LD16_addrnn_reg(m_registers.HL); })
Z80_OPCODE(23, true, "INC HL", { INC16_reg(&m_registers.HL); })
Z80_OPCODE(24, true, "INC H", { INC8_reg(&m_registers.H()); })
Z80_OPCODE(25, true, "DEC H", { DEC8_reg(&m_registers.H()); })
Z80_OPCODE(26, true, "LD H, %n", { LD8_reg_n(&m_registers.H()); })
Z80_OPCODE(27, true, "DAA", { DAA(); })
Z80_OPCODE(28, true, "JR Z, %n", { JR_condition_n(m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(29, true, "ADD HL, HL", { ADD16_reg_reg(&m_registers.HL, m_registers.HL); })
Z80_OPCODE(2A, true, "LD HL, (%nn)", { LD16_reg_addrnn(&m_registers.HL); })
Z80_OPCODE(2B, true, "DEC HL", { DEC16_reg(&m_registers.HL); })
Z80_OPCODE(2C, true, "INC L", { INC8_reg(&m_registers.L()); })
Z80_OPCODE(2D, true, "DEC L", { DEC8_reg(&m_registers.L()); })
Z80_OPCODE(2E, true, "LD L, %n", { LD8_reg_n(&m_registers.L()); })
Z80_OPCODE(2F, true, "CPL", { CPL(); })
Z80_OPCODE(30, true, "JR NC, %n", { JR_condition_n(!m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(31, true, "LD SP, %nn", { LD16_reg_nn(&m_registers.SP); })
Z80_OPCODE(32, true, "LD (%nn), A", { LD8_addrnn_reg(m_registers.A()); })
Z80_OPCODE(33, true, "INC SP", { INC16_reg(&m_registers.SP); })
Z80_OPCODE(34, true, "INC (HL)", { INC8_addrreg(m_registers.HL); })
Z80_OPCODE(35, true, "DEC (HL)", { DEC8_addrreg(m_registers.HL); })
Z80_OPCODE(36, true, "LD (HL), %n", { LD8_addrreg_n(m_registers.HL); })
Z80_OPCODE(37, true, "SCF", { SCF(); })
Z80_OPCODE(38, true, "JR C, %n", { JR_condition_n(m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(39, true, "ADD HL, SP", { ADD16_reg_reg(&m_registers.HL, m_registers.SP); })
Z80_OPCODE(3A, true, "LD A, (%nn)", { LD8_reg_addrnn(&m_registers.A()); })
Z80_OPCODE(3B, true, "DEC SP", { DEC16_reg(&m_registers.SP); })
Z80_OPCODE(3C, true, "INC A", { INC8_reg(&m_registers.A()); })
Z80_OPCODE(3D, true, "DEC A", { DEC8_reg(&m_registers.A()); })
Z80_OPCODE(3E, true, "LD A, %n", { LD8_reg_n(&m_registers.A()); })
Z80_OPCODE(3F, true, "CCF", { CCF(); })
Z80_OPCODE(40, true, "LD B, B", { LD8_reg_reg(&m_registers.B(), m_registers.B()); })
Z80_OPCODE(41, true, "LD B, C", { LD8_reg_reg(&m_registers.B(), m_registers.C()); })
Z80_OPCODE(42, true, "LD B, D", { LD8_reg_reg(&m_registers.B(), m_registers.D()); })
Z80_OPCODE(43, true, "LD B, E", { LD8_reg_reg(&m_registers.B(), m_registers.E()); })
Z80_OPCODE(44, true, "LD B, H", { LD8_reg_reg(&m_registers.B(), m_registers.H()); })
Z80_OPCODE(45, true, "LD B, L", { LD8_reg_reg(&m_registers.B(), m_registers.L()); })
Z80_OPCODE(46, true, "LD B, (HL)", { LD8_reg_addrreg(&m_registers.B(), m_registers.HL); })
Z80_OPCODE(47, true, "LD B, A", { LD8_reg_reg(&m_registers.B(), m_registers.A()); })
Z80_OPCODE(48, true, "LD C, B", { LD8_reg_reg(&m_registers.C(), m_registers.B()); })
Z80_OPCODE(49, true, "LD C, C", { LD8_reg_reg(&m_registers.C(), m_registers.C()); })
Z80_OPCODE(4A, true, "LD C, D", { LD8_reg_reg(&m_registers.C(), m_registers.D()); })
Z80_OPCODE(4B, true, "LD C, E", { LD8_reg_reg(&m_registers.C(), m_registers.E()); })
Z80_OPCODE(4C, true, "LD C, H", { LD8_reg_reg(&m_registers.C(), m_registers.H()); })
Z80_OPCODE(4D, true, "LD C, L", { LD8_reg_reg(&m_registers.C(), m_registers.L()); })
Z80_OPCODE(4E, true, "LD C, (HL)", { LD8_reg_addrreg(&m_registers.C(), m_registers.HL); })
Z80_OPCODE(4F, true, "LD C, A", { LD8_reg_reg(&m_registers.C(), m_registers.A()); })
Z80_OPCODE(50, true, "LD D, B", { LD8_reg_reg(&m_registers.D(), m_registers.B()); })
Z80_OPCODE(51, true, "LD D, C", { LD8_reg_reg(&m_registers.D(), m_registers.C()); })
Z80_OPCODE(52, true, "LD D, D", { LD8_reg_reg(&m_registers.D(), m_registers.D()); })
Z80_OPCODE(53, true, "LD D, E", { LD8_reg_reg(&m_registers.D(), m_registers.E()); })
Z80_OPCODE(54, true, "LD D, H", { LD8_reg_reg(&m_registers.D(), m_registers.H()); })
Z80_OPCODE(55, true, "LD D, L", { LD8_reg_reg(&m_registers.D(), m_registers.L()); })
Z80_OPCODE(56, true, "LD D, (HL)", { LD8_reg_addrreg(&m_registers.D(), m_registers.HL); })
Z80_OPCODE(57, true, "LD D, A", { LD8_reg_reg(&m_registers.D(), m_registers.A()); })
Z80_OPCODE(58, true, "LD E, B", { LD8_reg_reg(&m_registers.E(), m_registers.B()); })
Z80_OPCODE(59, true, "LD E, C", { LD8_reg_reg(&m_registers.E(), m_registers.C()); })
Z80_OPCODE(5A, true, "LD E, D", { LD8_reg_reg(&m_registers.E(), m_registers.D()); })
Z80_OPCODE(5B, true, "LD E, E", { LD8_reg_reg(&m_registers.E(), m_registers.E()); })
Z80_OPCODE(5C, true, "LD E, H", { LD8_reg_reg(&m_registers.E(), m_registers.H()); })
Z80_OPCODE(5D, true, "LD E, L", { LD8_reg_reg(&m_registers.E(), m_registers.L()); })
Z80_OPCODE(5E, true, "LD E, (HL)", { LD8_reg_addrreg(&m_registers.E(), m_registers.HL); })
Z80_OPCODE(5F, true, "LD E, A", { LD8_reg_reg(&m_registers.E(), m_registers.A()); })
Z80_OPCODE(60, true, "LD H, B", { LD8_reg_reg(&m_registers.H(), m_registers.B()); })
Z80_OPCODE(61, true, "LD H, C", { LD8_reg_reg(&m_registers.H(), m_registers.C()); })
Z80_OPCODE(62, true, "LD H, D", { LD8_reg_reg(&m_registers.H(), m_registers.D()); })
Z80_OPCODE(63, true, "LD H, E", { LD8_reg_reg(&m_registers.H(), m_registers.E()); })
Z80_OPCODE(64, true, "LD H, H", { LD8_reg_reg(&m_registers.H(), m_registers.H()); })
Z80_OPCODE(65, true, "LD H, L", { LD8_reg_reg(&m_registers.H(), m_registers.L()); })
Z80_OPCODE(66, true, "LD H, (HL)", { LD8_reg_addrreg(&m_registers.H(), m_registers.HL); })
Z80_OPCODE(67, true, "LD H, A", { LD8_reg_reg(&m_registers.H(), m_registers.A()); })
Z80_OPCODE(68, true, "LD L, B", { LD8_reg_reg(&m_registers.L(), m_registers.B()); })
Z80_OPCODE(69, true, "LD L, C", { LD8_reg_reg(&m_registers.L(), m_registers.C()); })
Z80_OPCODE(6A, true, "LD L, D", { LD8_reg_reg(&m_registers.L(), m_registers.D()); })
Z80_OPCODE(6B, true, "LD L, E", { LD8_reg_reg(&m_registers.L(), m_registers.E()); })
Z80_OPCODE(6C, true, "LD L, H", { LD8_reg_reg(&m_registers.L(), m_registers.H()); })
Z80_OPCODE(6D, true, "LD L, L", { LD8_reg_reg(&m_registers.L(), m_registers.L()); })
Z80_OPCODE(6E, true, "LD L, (HL)", { LD8_reg_addrreg(&m_registers.L(), m_registers.HL); })
Z80_OPCODE(6F, true, "LD L, A", { LD8_reg_reg(&m_registers.L(), m_registers.A()); })
Z80_OPCODE(70, true, "LD (HL), B", { LD8_addrreg_valuereg(m_registers.HL, m_registers.B()); })
Z80_OPCODE(71, true, "LD (HL), C", { LD8_addrreg_valuereg(m_registers.HL, m_registers.C()); })
Z80_OPCODE(72, true, "LD (HL), D", { LD8_addrreg_valuereg(m_registers.HL, m_registers.D()); })
Z80_OPCODE(73, true, "LD (HL), E", { LD8_addrreg_valuereg(m_registers.HL, m_registers.E()); })
Z80_OPCODE(74, true, "LD (HL), H", { LD8_addrreg_valuereg(m_registers.HL, m_registers.H()); })
Z80_OPCODE(75, true, "LD (HL), L", { LD8_addrreg_valuereg(m_registers.HL, m_registers.L()); })
Z80_OPCODE(76, true, "HALT", { HALT(); })
Z80_OPCODE(77, true, "LD (HL), A", { LD8_addrreg_valuereg(m_registers.HL, m_registers.A()); })
Z80_OPCODE(78, true, "LD A, B", { LD8_reg_reg(&m_registers.A(), m_registers.B()); })
Z80_OPCODE(79, true, "LD A, C", { LD8_reg_reg(&m_registers.A(), m_registers.C()); })
Z80_OPCODE(7A, true, "LD A, D", { LD8_reg_reg(&m_registers.A(), m_registers.D()); })
Z80_OPCODE(7B, true, "LD A, E", { LD8_reg_reg(&m_registers.A(), m_registers.E()); })
Z80_OPCODE(7C, true, "LD A, H", { LD8_reg_reg(&m_registers.A(), m_registers.H()); })
Z80_OPCODE(7D, true, "LD A, L", { LD8_reg_reg(&m_registers.A(), m_registers.L()); })
Z80_OPCODE(7E, true, "LD A, (HL)", { LD8_reg_addrreg(&m_registers.A(), m_registers.HL); })
Z80_OPCODE(7F, true, "LD A, A", { LD8_reg_reg(&m_registers.A(), m_registers.A()); })
Z80_OPCODE(80, true, "ADD A, B", { ADD8_reg_reg(&m_registers.A(), m_registers.B(), 0); })
Z80_OPCODE(81, true, "ADD A, C", { ADD8_reg_reg(&m_registers.A(), m_registers.C(), 0); })
Z80_OPCODE(82, true, "ADD A, D", { ADD8_reg_reg(&m_registers.A(), m_registers.D(), 0); })
Z80_OPCODE(83, true, "ADD A, E", { ADD8_reg_reg(&m_registers.A(), m_registers.E(), 0); })
Z80_OPCODE(84, true, "ADD A, H", { ADD8_reg_reg(&m_registers.A(), m_registers.H(), 0); })
Z80_OPCODE(85, true, "ADD A, L", { ADD8_reg_reg(&m_registers.A(), m_registers.L(), 0); })
Z80_OPCODE(86, true, "ADD A, (HL)", { ADD8_reg_addrreg(&m_registers.A(), m_registers.HL, 0); })
Z80_OPCODE(87, true, "ADD A, A", { ADD8_reg_reg(&m_registers.A(), m_registers.A(), 0); })
Z80_OPCODE(88, true, "ADC A, B", { ADD8_reg_reg(&m_registers.A(), m_registers.B(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(89, true, "ADC A, C", { ADD8_reg_reg(&m_registers.A(), m_registers.C(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8A, true, "ADC A, D", { ADD8_reg_reg(&m_registers.A(), m_registers.D(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8B, true, "ADC A, E", { ADD8_reg_reg(&m_registers.A(), m_registers.E(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8C, true, "ADC A, H", { ADD8_reg_reg(&m_registers.A(), m_registers.H(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8D, true, "ADC A, L", { ADD8_reg_reg(&m_registers.A(), m_registers.L(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8E, true, "ADC A, (HL)", { ADD8_reg_addrreg(&m_registers.A(), m_registers.HL, m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(8F, true, "ADC A, A", { ADD8_reg_reg(&m_registers.A(), m_registers.A(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(90, true, "SUB B", { SUB8_reg(m_registers.B(), 0); })
Z80_OPCODE(91, true, "SUB C", { SUB8_reg(m_registers.C(), 0); })
Z80_OPCODE(92, true, "SUB D", { SUB8_reg(m_registers.D(), 0); })
Z80_OPCODE(93, true, "SUB E", { SUB8_reg(m_registers.E(), 0); })
Z80_OPCODE(94, true, "SUB H", { SUB8_reg(m_registers.H(), 0); })
Z80_OPCODE(95, true, "SUB L", { SUB8_reg(m_registers.L(), 0); })
Z80_OPCODE(96, true, "SUB (HL)", { SUB8_addrreg(m_registers.HL, 0); })
Z80_OPCODE(97, true, "SUB A", { SUB8_reg(m_registers.A(), 0); })
Z80_OPCODE(98, true, "SBC A, B", { SUB8_reg(m_registers.B(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(99, true, "SBC A, C", { SUB8_reg(m_registers.C(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9A, true, "SBC A, D", { SUB8_reg(m_registers.D(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9B, true, "SBC A, E", { SUB8_reg(m_registers.E(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9C, true, "SBC A, H", { SUB8_reg(m_registers.H(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9D, true, "SBC A, L", { SUB8_reg(m_registers.L(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9E, true, "SBC A, (HL)", { SUB8_addrreg(m_registers.HL, m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(9F, true, "SBC A, A", { SUB8_reg(m_registers.A(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(A0, true, "AND B", { AND_reg(m_registers.B()); })
Z80_OPCODE(A1, true, "AND C", { AND_reg(m_registers.C()); })
Z80_OPCODE(A2, true, "AND D", { AND_reg(m_registers.D()); })
Z80_OPCODE(A3, true, "AND E", { AND_reg(m_registers.E()); })
Z80_OPCODE(A4, true, "AND H", { AND_reg(m_registers.H()); })
Z80_OPCODE(A5, true, "AND L", { AND_reg(m_registers.L()); })
Z80_OPCODE(A6, true, "AND (HL)", { AND_addrreg(m_registers.HL); })
Z80_OPCODE(A7, true, "AND A", { AND_reg(m_registers.A()); })
Z80_OPCODE(A8, true, "XOR B", { XOR_reg(m_registers.B()); })
Z80_OPCODE(A9, true, "XOR C", { XOR_reg(m_registers.C()); })
Z80_OPCODE(AA, true, "XOR D", { XOR_reg(m_registers.D()); })
Z80_OPCODE(AB, true, "XOR E", { XOR_reg(m_registers.E()); })
Z80_OPCODE(AC, true, "XOR H", { XOR_reg(m_registers.H()); })
Z80_OPCODE(AD, true, "XOR L", { XOR_reg(m_registers.L()); })
Z80_OPCODE(AE, true, "XOR (HL)", { XOR_addrreg(m_registers.HL); })
Z80_OPCODE(AF, true, "XOR A", { XOR_reg(m_registers.A()); })
Z80_OPCODE(B0, true, "OR B", { OR_reg(m_registers.B()); })
Z80_OPCODE(B1, true, "OR C", { OR_reg(m_registers.C()); })
Z80_OPCODE(B2, true, "OR D", { OR_reg(m_registers.D()); })
Z80_OPCODE(B3, true, "OR E", { OR_reg(m_registers.E()); })
Z80_OPCODE(B4, true, "OR H", { OR_reg(m_registers.H()); })
Z80_OPCODE(B5, true, "OR L", { OR_reg(m_registers.L()); })
Z80_OPCODE(B6, true, "OR (HL)", { OR_addrreg(m_registers.HL); })
Z80_OPCODE(B7, true, "OR A", { OR_reg(m_registers.A()); })
Z80_OPCODE(B8, true, "CP B", { CP_reg(m_registers.B()); })
Z80_OPCODE(B9, true, "CP C", { CP_reg(m_registers.C()); })
Z80_OPCODE(BA, true, "CP D", { CP_reg(m_registers.D()); })
Z80_OPCODE(BB, true, "CP E", { CP_reg(m_registers.E()); })
Z80_OPCODE(BC, true, "CP H", { CP_reg(m_registers.H()); })
Z80_OPCODE(BD, true, "CP L", { CP_reg(m_registers.L()); })
Z80_OPCODE(BE, true, "CP (HL)", { CP_addrreg(m_registers.HL); })
Z80_OPCODE(BF, true, "CP A", { CP_reg(m_registers.A()); })
Z80_OPCODE(C0, true, "RET NZ", { RET_condition(!m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(C1, true, "POP BC", { POP(&m_registers.BC); })
Z80_OPCODE(C2, true, "JP NZ, %nn", { JP_condition_nn(!m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(C3, true, "JP %nn", { JP_nn(); })
Z80_OPCODE(C4, true, "CALL NZ, %nn", { CALL_condition_nn(!m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(C5, true, "PUSH BC", { PUSH(m_registers.BC); })
Z80_OPCODE(C6, true, "ADD A, %n", { ADD8_reg_n(&m_registers.A(), 0); })
Z80_OPCODE(C7, true, "RST 00h", { RST_p(0x00); })
Z80_OPCODE(C8, true, "RET Z", { RET_condition(m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(C9, true, "RET", { RET(); })
Z80_OPCODE(CA, true, "JP Z, %nn", { JP_condition_nn(m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(CB, false, "<CB prefix>", { ProcessPrefixByte(0xCB); })
Z80_OPCODE(CC, true, "CALL Z, %nn", { CALL_condition_nn(m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(CD, true, "CALL %nn", { CALL_nn(); })
Z80_OPCODE(CE, true, "ADC A, %n", { ADD8_reg_n(&m_registers.A(), m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(CF, true, "RST 08h", { RST_p(0x08); })
Z80_OPCODE(D0, true, "RET NC", { RET_condition(!m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(D1, true, "POP DE", { POP(&m_registers.DE); })
Z80_OPCODE(D2, true, "JP NC, %nn", { JP_condition_nn(!m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(D3, true, "OUT (%n), A", { OUT_n(); })
Z80_OPCODE(D4, true, "CALL NC, %nn", { CALL_condition_nn(!m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(D5, true, "PUSH DE", { PUSH(m_registers.DE); })
Z80_OPCODE(D6, true, "SUB %n", { SUB8_n(0); })
Z80_OPCODE(D7, true, "RST 10h", { RST_p(0x10); })
Z80_OPCODE(D8, true, "RET C", { RET_condition(m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(D9, true, "EXX", { EXX(); })
Z80_OPCODE(DA, true, "JP C, %nn", { JP_condition_nn(m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(DB, true, "IN A, (%n)", { IN_n(); })
Z80_OPCODE(DC, true, "CALL C, %nn", { CALL_condition_nn(m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(DD, false, "<DD prefix>", { ProcessPrefixByte(0xDD); })
Z80_OPCODE(DE, true, "SBC A, %n", { SUB8_n(m_registers.GetFlag(Registers::Flag_C) ? 1 : 0); })
Z80_OPCODE(DF, true, "RST 18h", { RST_p(0x18); })
Z80_OPCODE(E0, true, "RET PO", { RET_condition(!m_registers.GetFlag(Registers::Flag_PV)); })
Z80_OPCODE(E1, true, "POP HL", { POP(&m_registers.HL); })
Z80_OPCODE(E2, true, "JP PO, %nn", { JP_condition_nn(!m_registers.GetFlag(Registers::Flag_PV)); })
Z80_OPCODE(E3, true, "EX (SP), HL", { EX_addrreg_reg(m_registers.SP, &m_registers.HL); })
Z80_OPCODE(E4, true, "CALL PO, %nn", { CALL_condition_nn(!m_registers.GetFlag(Registers::Flag_PV)); })
Z80_OPCODE(E5, true, "PUSH HL", { PUSH(m_registers.HL); })
Z80_OPCODE(E6, true, "AND %n", { AND_n(); })
Z80_OPCODE(E7, true, "RST 20h", { RST_p(0x20); })
Z80_OPCODE(E8, true, "RET PE", { RET_condition(m_registers.GetFlag(Registers::Flag_PV)); })
Z80_OPCODE(E9, true, "JP (HL)", { JP_reg(m_registers.HL); })
Z80_OPCODE(EA, true, "JP PE, %nn", { JP_condition_nn(m_registers.GetFlag(Registers::Flag_PV)); })
Z80_OPCODE(EB, true, "EX DE, HL", { EX_reg_reg(&m_registers.DE, &m_registers.HL); })
Z80_OPCODE(EC, true, "CALL PE, %nn", { CALL_condition_nn(m_registers.GetFlag(Registers::Flag_PV)); })
Z80_OPCODE(ED, false, "<ED prefix>", { ProcessPrefixByte(0xED); })
Z80_OPCODE(EE, true, "XOR %n", { XOR_n(); })
Z80_OPCODE(EF, true, "RST 28h", { RST_p(0x28); })
Z80_OPCODE(F0, true, "RET P", { RET_condition(!m_registers.GetFlag(Registers::Flag_S)); })
Z80_OPCODE(F1, true, "POP AF", { POP(&m_registers.AF); })
Z80_OPCODE(F2, true, "JP P, %nn", { JP_condition_nn(!m_registers.GetFlag(Registers::Flag_S)); })
Z80_OPCODE(F3, true, "DI", { DI(); })
Z80_OPCODE(F4, true, "CALL P, %nn", { CALL_condition_nn(!m_registers.GetFlag(Registers::Flag_S)); })
Z80_OPCODE(F5, true, "PUSH AF", { PUSH(m_registers.AF); })
Z80_OPCODE(F6, true, "OR %n", { OR_n(); })
Z80_OPCODE(F7, true, "RST 30h", { RST_p(0x30); })
Z80_OPCODE(F8, true, "RET M", { RET_condition(m_registers.GetFlag(Registers::Flag_S)); })
Z80_OPCODE(F9, true, "LD SP, HL", { LD16_reg_reg(&m_registers.SP, m_registers.HL); })
Z80_OPCODE(FA, true, "JP M, %nn", { JP_condition_nn(m_registers.GetFlag(Registers::Flag_S)); })
Z80_OPCODE(FB, true, "EI", { EI(); })
Z80_OPCODE(FC, true, "CALL M, %nn", { CALL_condition_nn(m_registers.GetFlag(Registers::Flag_S)); })
Z80_OPCODE(FD, false, "<FD prefix>", { ProcessPrefixByte(0xFD); })
Z80_OPCODE(FE, true, "CP %n", { CP_n(); })
Z80_OPCODE(FF, true, "RST 38h", { RST_p(0x38); })
