//------------------------------------------------------------------------------
// *** DO NOT INCLUDE DIRECTLY ***
//
// These macros generate code and populate several tables related to opcodes automatically.
//------------------------------------------------------------------------------

Z80_OPCODE(00, false, "NOP", { /* Do nothing. */ })
Z80_OPCODE(01, false, "LD BC, %nn", { LD16_reg_nn(&m_registers.BC); })
Z80_OPCODE(02, false, "LD (BC), A", { LD8_addrreg_valuereg(m_registers.BC, m_registers.A()); })
Z80_OPCODE(03, false, "INC BC", { INC16_reg(&m_registers.BC); })
Z80_OPCODE(04, false, "INC B", { INC8_reg(&m_registers.B()); })
Z80_OPCODE(05, false, "DEC B", { DEC8_reg(&m_registers.B()); })
Z80_OPCODE(06, false, "LD B, %n", { LD8_reg_n(&m_registers.B()); })
Z80_OPCODE(07, false, "RLCA", { RLC(&m_registers.A()); })
Z80_OPCODE(08, false, "EX AF, AF'", { EX_reg_reg(&m_registers.AF, &m_registers.altAF); })
Z80_OPCODE(09, false, "ADD HL, BC", { ADD16_reg_reg(&m_registers.HL, m_registers.BC); })
Z80_OPCODE(0A, false, "LD A,(BC)", { LD8_reg_mem(&m_registers.A(), m_registers.BC); })
Z80_OPCODE(0B, false, "DEC BC", { DEC16_reg(&m_registers.BC); })
Z80_OPCODE(0C, false, "INC C", { INC8_reg(&m_registers.C()); })
Z80_OPCODE(0D, false, "DEC C", { DEC8_reg(&m_registers.C()); })
Z80_OPCODE(0E, false, "LD C, %n", { LD8_reg_n(&m_registers.C()); })
Z80_OPCODE(0F, false, "RRCA", { RRC(&m_registers.A()); })
Z80_OPCODE(10, false, "DJNZ %n", { DJNZ_n(); })
Z80_OPCODE(11, false, "LD DE, %nn", { LD16_reg_nn(&m_registers.DE); })
Z80_OPCODE(12, false, "LD (DE), A", { LD8_addrreg_valuereg(m_registers.DE, m_registers.A()); })
Z80_OPCODE(13, false, "INC DE", { INC16_reg(&m_registers.DE); })
Z80_OPCODE(14, false, "INC D", { INC8_reg(&m_registers.D()); })
Z80_OPCODE(15, false, "DEC D", { DEC8_reg(&m_registers.D()); })
Z80_OPCODE(16, false, "LD D, %n", { LD8_reg_n(&m_registers.D()); })
Z80_OPCODE(17, false, "RLA", { RL(&m_registers.A()); })
Z80_OPCODE(18, false, "JR %n", { JR_n(); })
Z80_OPCODE(19, false, "ADD HL, DE", { ADD16_reg_reg(&m_registers.HL, m_registers.DE); })
Z80_OPCODE(1A, false, "LD A, (DE)", { LD8_reg_mem(&m_registers.A(), m_registers.DE); })
Z80_OPCODE(1B, false, "DEC DE", { DEC16_reg(&m_registers.DE); })
Z80_OPCODE(1C, false, "INC E", { INC8_reg(&m_registers.E()); })
Z80_OPCODE(1D, false, "DEC E", { DEC8_reg(&m_registers.E()); })
Z80_OPCODE(1E, false, "LD E, %n", { LD8_reg_n(&m_registers.E()); })
Z80_OPCODE(1F, false, "RRA", { RR(&m_registers.A()); })
Z80_OPCODE(20, false, "JR NZ, %n", { JR_condition_n(!m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(21, false, "LD HL, %nn", { LD16_reg_nn(&m_registers.HL); })
Z80_OPCODE(22, false, "LD (%nn), HL", { LD16_addrnn_reg(m_registers.HL); })
Z80_OPCODE(23, false, "INC HL", { INC16_reg(&m_registers.HL); })
Z80_OPCODE(24, false, "INC H", { INC8_reg(&m_registers.H()); })
Z80_OPCODE(25, false, "DEC H", { DEC8_reg(&m_registers.H()); })
Z80_OPCODE(26, false, "LD H, %n", { LD8_reg_n(&m_registers.H()); })
Z80_OPCODE(27, false, "DAA", { DAA(); })
Z80_OPCODE(28, false, "JR Z, %n", { JR_condition_n(m_registers.GetFlag(Registers::Flag_Z)); })
Z80_OPCODE(29, false, "ADD HL, HL", { ADD16_reg_reg(&m_registers.HL, m_registers.HL); })
Z80_OPCODE(2A, false, "LD HL, (%nn)", { LD16_reg_addrnn(&m_registers.HL); })
Z80_OPCODE(2B, false, "DEC HL", { DEC16_reg(&m_registers.HL); })
Z80_OPCODE(2C, false, "INC L", { INC8_reg(&m_registers.L()); })
Z80_OPCODE(2D, false, "DEC L", { DEC8_reg(&m_registers.L()); })
Z80_OPCODE(2E, false, "LD L, %n", { LD8_reg_n(&m_registers.L()); })
Z80_OPCODE(2F, false, "CPL", { CPL(); })
Z80_OPCODE(30, false, "JR NC, %n", { JR_condition_n(!m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(31, false, "LD SP, %nn", { LD16_reg_nn(&m_registers.SP); })
Z80_OPCODE(32, false, "LD (%nn), A", { LD8_addrnn_reg(m_registers.A()); })
Z80_OPCODE(33, false, "INC SP", { INC16_reg(&m_registers.SP); })
Z80_OPCODE(34, false, "INC (HL)", { INC8_addrreg(m_registers.HL); })
Z80_OPCODE(35, false, "DEC (HL)", { DEC8_addrreg(m_registers.HL); })
Z80_OPCODE(36, false, "LD (HL), %n", { LD8_addrreg_n(m_registers.HL); })
Z80_OPCODE(37, false, "SCF", { SCF(); })
Z80_OPCODE(38, false, "JR C, %n", { JR_condition_n(m_registers.GetFlag(Registers::Flag_C)); })
Z80_OPCODE(39, false, "ADD HL, SP", { ADD16_reg_reg(&m_registers.HL, m_registers.SP); })
Z80_OPCODE(40, false, "LD B, B", { LD8_reg_reg(&m_registers.B(), m_registers.B()); })
Z80_OPCODE(41, false, "LD B, C", { LD8_reg_reg(&m_registers.B(), m_registers.C()); })
Z80_OPCODE(42, false, "LD B, D", { LD8_reg_reg(&m_registers.B(), m_registers.D()); })
Z80_OPCODE(43, false, "LD B, E", { LD8_reg_reg(&m_registers.B(), m_registers.E()); })
Z80_OPCODE(44, false, "LD B, H", { LD8_reg_reg(&m_registers.B(), m_registers.H()); })
Z80_OPCODE(45, false, "LD B, L", { LD8_reg_reg(&m_registers.B(), m_registers.L()); })
Z80_OPCODE(46, false, "LD B, (HL)", { LD8_reg_addrreg(&m_registers.B(), m_registers.HL); })
Z80_OPCODE(47, false, "LD B, A", { LD8_reg_reg(&m_registers.B(), m_registers.A()); })
Z80_OPCODE(48, false, "LD C, B", { LD8_reg_reg(&m_registers.C(), m_registers.B()); })
Z80_OPCODE(49, false, "LD C, C", { LD8_reg_reg(&m_registers.C(), m_registers.C()); })
Z80_OPCODE(4A, false, "LD C, D", { LD8_reg_reg(&m_registers.C(), m_registers.D()); })
Z80_OPCODE(4B, false, "LD C, E", { LD8_reg_reg(&m_registers.C(), m_registers.E()); })
Z80_OPCODE(4C, false, "LD C, H", { LD8_reg_reg(&m_registers.C(), m_registers.H()); })
Z80_OPCODE(4D, false, "LD C, L", { LD8_reg_reg(&m_registers.C(), m_registers.L()); })
Z80_OPCODE(4E, false, "LD C, (HL)", { LD8_reg_addrreg(&m_registers.C(), m_registers.HL); })
Z80_OPCODE(4F, false, "LD C, A", { LD8_reg_reg(&m_registers.C(), m_registers.A()); })
Z80_OPCODE(50, false, "LD D, B", { LD8_reg_reg(&m_registers.D(), m_registers.B()); })
Z80_OPCODE(51, false, "LD D, C", { LD8_reg_reg(&m_registers.D(), m_registers.C()); })
Z80_OPCODE(52, false, "LD D, D", { LD8_reg_reg(&m_registers.D(), m_registers.D()); })
Z80_OPCODE(53, false, "LD D, E", { LD8_reg_reg(&m_registers.D(), m_registers.E()); })
Z80_OPCODE(54, false, "LD D, H", { LD8_reg_reg(&m_registers.D(), m_registers.H()); })
Z80_OPCODE(55, false, "LD D, L", { LD8_reg_reg(&m_registers.D(), m_registers.L()); })
Z80_OPCODE(56, false, "LD D, (HL)", { LD8_reg_addrreg(&m_registers.D(), m_registers.HL); })
Z80_OPCODE(57, false, "LD D, A", { LD8_reg_reg(&m_registers.D(), m_registers.A()); })
Z80_OPCODE(58, false, "LD E, B", { LD8_reg_reg(&m_registers.E(), m_registers.B()); })
Z80_OPCODE(59, false, "LD E, C", { LD8_reg_reg(&m_registers.E(), m_registers.C()); })
Z80_OPCODE(5A, false, "LD E, D", { LD8_reg_reg(&m_registers.E(), m_registers.D()); })
Z80_OPCODE(5B, false, "LD E, E", { LD8_reg_reg(&m_registers.E(), m_registers.E()); })
Z80_OPCODE(5C, false, "LD E, H", { LD8_reg_reg(&m_registers.E(), m_registers.H()); })
Z80_OPCODE(5D, false, "LD E, L", { LD8_reg_reg(&m_registers.E(), m_registers.L()); })
Z80_OPCODE(5E, false, "LD E, (HL)", { LD8_reg_addrreg(&m_registers.E(), m_registers.HL); })
Z80_OPCODE(5F, false, "LD E, A", { LD8_reg_reg(&m_registers.E(), m_registers.A()); })
Z80_OPCODE(60, false, "LD H, B", { LD8_reg_reg(&m_registers.H(), m_registers.B()); })
Z80_OPCODE(61, false, "LD H, C", { LD8_reg_reg(&m_registers.H(), m_registers.C()); })
Z80_OPCODE(62, false, "LD H, D", { LD8_reg_reg(&m_registers.H(), m_registers.D()); })
Z80_OPCODE(63, false, "LD H, E", { LD8_reg_reg(&m_registers.H(), m_registers.E()); })
Z80_OPCODE(64, false, "LD H, H", { LD8_reg_reg(&m_registers.H(), m_registers.H()); })
Z80_OPCODE(65, false, "LD H, L", { LD8_reg_reg(&m_registers.H(), m_registers.L()); })
Z80_OPCODE(66, false, "LD H, (HL)", { LD8_reg_addrreg(&m_registers.H(), m_registers.HL); })
Z80_OPCODE(67, false, "LD H, A", { LD8_reg_reg(&m_registers.H(), m_registers.A()); })
Z80_OPCODE(68, false, "LD L, B", { LD8_reg_reg(&m_registers.L(), m_registers.B()); })
Z80_OPCODE(69, false, "LD L, C", { LD8_reg_reg(&m_registers.L(), m_registers.C()); })
Z80_OPCODE(6A, false, "LD L, D", { LD8_reg_reg(&m_registers.L(), m_registers.D()); })
Z80_OPCODE(6B, false, "LD L, E", { LD8_reg_reg(&m_registers.L(), m_registers.E()); })
Z80_OPCODE(6C, false, "LD L, H", { LD8_reg_reg(&m_registers.L(), m_registers.H()); })
Z80_OPCODE(6D, false, "LD L, L", { LD8_reg_reg(&m_registers.L(), m_registers.L()); })
Z80_OPCODE(6E, false, "LD L, (HL)", { LD8_reg_addrreg(&m_registers.L(), m_registers.HL); })
Z80_OPCODE(6F, false, "LD L, A", { LD8_reg_reg(&m_registers.L(), m_registers.A()); })
Z80_OPCODE(70, false, "LD (HL), B", { LD8_addrreg_valuereg(m_registers.HL, m_registers.B()); })
Z80_OPCODE(71, false, "LD (HL), C", { LD8_addrreg_valuereg(m_registers.HL, m_registers.C()); })
Z80_OPCODE(72, false, "LD (HL), D", { LD8_addrreg_valuereg(m_registers.HL, m_registers.D()); })
Z80_OPCODE(73, false, "LD (HL), E", { LD8_addrreg_valuereg(m_registers.HL, m_registers.E()); })
Z80_OPCODE(74, false, "LD (HL), H", { LD8_addrreg_valuereg(m_registers.HL, m_registers.H()); })
Z80_OPCODE(75, false, "LD (HL), L", { LD8_addrreg_valuereg(m_registers.HL, m_registers.L()); })
Z80_OPCODE(76, false, "HALT", { HALT(); })
Z80_OPCODE(77, false, "LD (HL), A", { LD8_addrreg_valuereg(m_registers.HL, m_registers.A()); })
Z80_OPCODE(78, false, "LD A, B", { LD8_reg_reg(&m_registers.A(), m_registers.B()); })
Z80_OPCODE(79, false, "LD A, C", { LD8_reg_reg(&m_registers.A(), m_registers.C()); })
Z80_OPCODE(7A, false, "LD A, D", { LD8_reg_reg(&m_registers.A(), m_registers.D()); })
Z80_OPCODE(7B, false, "LD A, E", { LD8_reg_reg(&m_registers.A(), m_registers.E()); })
Z80_OPCODE(7C, false, "LD A, H", { LD8_reg_reg(&m_registers.A(), m_registers.H()); })
Z80_OPCODE(7D, false, "LD A, L", { LD8_reg_reg(&m_registers.A(), m_registers.L()); })
Z80_OPCODE(7E, false, "LD A, (HL)", { LD8_reg_addrreg(&m_registers.A(), m_registers.HL); })
Z80_OPCODE(7F, false, "LD A, A", { LD8_reg_reg(&m_registers.A(), m_registers.A()); })
Z80_OPCODE(80, false, "ADD A, B", { ADD8_reg_reg(&m_registers.A(), m_registers.B()); })
Z80_OPCODE(81, false, "ADD A, C", { ADD8_reg_reg(&m_registers.A(), m_registers.C()); })
Z80_OPCODE(82, false, "ADD A, D", { ADD8_reg_reg(&m_registers.A(), m_registers.D()); })
Z80_OPCODE(83, false, "ADD A, E", { ADD8_reg_reg(&m_registers.A(), m_registers.E()); })
Z80_OPCODE(84, false, "ADD A, H", { ADD8_reg_reg(&m_registers.A(), m_registers.H()); })
Z80_OPCODE(85, false, "ADD A, L", { ADD8_reg_reg(&m_registers.A(), m_registers.L()); })
Z80_OPCODE(86, false, "ADD A, (HL)", { ADD8_reg_addrreg(&m_registers.A(), m_registers.HL); })
Z80_OPCODE(87, false, "ADD A, A", { ADD8_reg_reg(&m_registers.A(), m_registers.A()); })
