//------------------------------------------------------------------------------
// *** DO NOT INCLUDE DIRECTLY ***
//
// These macros generate code and populate several tables related to opcodes automatically.
//------------------------------------------------------------------------------

Z80_OPCODE(00, true, "RLC B", { RLC_reg(&m_registers.B()); })
Z80_OPCODE(01, true, "RLC C", { RLC_reg(&m_registers.C()); })
Z80_OPCODE(02, true, "RLC D", { RLC_reg(&m_registers.D()); })
Z80_OPCODE(03, true, "RLC E", { RLC_reg(&m_registers.E()); })
Z80_OPCODE(04, true, "RLC H", { RLC_reg(&m_registers.H()); })
Z80_OPCODE(05, true, "RLC L", { RLC_reg(&m_registers.L()); })
Z80_OPCODE(06, true, "RLC (HL)", { RLC_addrreg(m_registers.HL); })
Z80_OPCODE(07, true, "RLC A", { RLC_reg(&m_registers.A()); })
Z80_OPCODE(08, true, "RRC B", { RRC_reg(&m_registers.B()); })
Z80_OPCODE(09, true, "RRC C", { RRC_reg(&m_registers.C()); })
Z80_OPCODE(0A, true, "RRC D", { RRC_reg(&m_registers.D()); })
Z80_OPCODE(0B, true, "RRC E", { RRC_reg(&m_registers.E()); })
Z80_OPCODE(0C, true, "RRC H", { RRC_reg(&m_registers.H()); })
Z80_OPCODE(0D, true, "RRC L", { RRC_reg(&m_registers.L()); })
Z80_OPCODE(0E, true, "RRC (HL)", { RRC_addrreg(m_registers.HL); })
Z80_OPCODE(0F, true, "RRC A", { RRC_reg(&m_registers.A()); })
Z80_OPCODE(10, true, "RL B", { RL_reg(&m_registers.B()); })
Z80_OPCODE(11, true, "RL C", { RL_reg(&m_registers.C()); })
Z80_OPCODE(12, true, "RL D", { RL_reg(&m_registers.D()); })
Z80_OPCODE(13, true, "RL E", { RL_reg(&m_registers.E()); })
Z80_OPCODE(14, true, "RL H", { RL_reg(&m_registers.H()); })
Z80_OPCODE(15, true, "RL L", { RL_reg(&m_registers.L()); })
Z80_OPCODE(16, true, "RL (HL)", { RL_addrreg(m_registers.HL); })
Z80_OPCODE(17, true, "RL A", { RL_reg(&m_registers.A()); })
Z80_OPCODE(18, true, "RR B", { RR_reg(&m_registers.B()); })
Z80_OPCODE(19, true, "RR C", { RR_reg(&m_registers.C()); })
Z80_OPCODE(1A, true, "RR D", { RR_reg(&m_registers.D()); })
Z80_OPCODE(1B, true, "RR E", { RR_reg(&m_registers.E()); })
Z80_OPCODE(1C, true, "RR H", { RR_reg(&m_registers.H()); })
Z80_OPCODE(1D, true, "RR L", { RR_reg(&m_registers.L()); })
Z80_OPCODE(1E, true, "RR (HL)", { RR_addrreg(m_registers.HL); })
Z80_OPCODE(1F, true, "RR A", { RR_reg(&m_registers.A()); })
Z80_OPCODE(20, true, "SLA B", { SL_reg(&m_registers.B(), false); })
Z80_OPCODE(21, true, "SLA C", { SL_reg(&m_registers.C(), false); })
Z80_OPCODE(22, true, "SLA D", { SL_reg(&m_registers.D(), false); })
Z80_OPCODE(23, true, "SLA E", { SL_reg(&m_registers.E(), false); })
Z80_OPCODE(24, true, "SLA H", { SL_reg(&m_registers.H(), false); })
Z80_OPCODE(25, true, "SLA L", { SL_reg(&m_registers.L(), false); })
Z80_OPCODE(26, true, "SLA (HL)", { SL_addrreg(m_registers.HL, false); })
Z80_OPCODE(27, true, "SLA A", { SL_reg(&m_registers.A(), false); })
Z80_OPCODE(28, true, "SRA B", { SR_reg(&m_registers.B(), (m_registers.B() & 0x80) != 0); })
Z80_OPCODE(29, true, "SRA C", { SR_reg(&m_registers.C(), (m_registers.C() & 0x80) != 0); })
Z80_OPCODE(2A, true, "SRA D", { SR_reg(&m_registers.D(), (m_registers.D() & 0x80) != 0); })
Z80_OPCODE(2B, true, "SRA E", { SR_reg(&m_registers.E(), (m_registers.E() & 0x80) != 0); })
Z80_OPCODE(2C, true, "SRA H", { SR_reg(&m_registers.H(), (m_registers.H() & 0x80) != 0); })
Z80_OPCODE(2D, true, "SRA L", { SR_reg(&m_registers.L(), (m_registers.L() & 0x80) != 0); })
Z80_OPCODE(2E, true, "SRA (HL)", { SRA_addrreg(m_registers.HL); })
Z80_OPCODE(2F, true, "SRA A", { SR_reg(&m_registers.A(), (m_registers.A() & 0x80) != 0); })
Z80_OPCODE(30, true, "SLL B", { SL_reg(&m_registers.B(), true); })
Z80_OPCODE(31, true, "SLL C", { SL_reg(&m_registers.C(), true); })
Z80_OPCODE(32, true, "SLL D", { SL_reg(&m_registers.D(), true); })
Z80_OPCODE(33, true, "SLL E", { SL_reg(&m_registers.E(), true); })
Z80_OPCODE(34, true, "SLL H", { SL_reg(&m_registers.H(), true); })
Z80_OPCODE(35, true, "SLL L", { SL_reg(&m_registers.L(), true); })
Z80_OPCODE(36, true, "SLL (HL)", { SL_addrreg(m_registers.HL, true); })
Z80_OPCODE(37, true, "SLL A", { SL_reg(&m_registers.A(), true); })
Z80_OPCODE(38, true, "SRL B", { SR_reg(&m_registers.B(), false); })
Z80_OPCODE(39, true, "SRL C", { SR_reg(&m_registers.C(), false); })
Z80_OPCODE(3A, true, "SRL D", { SR_reg(&m_registers.D(), false); })
Z80_OPCODE(3B, true, "SRL E", { SR_reg(&m_registers.E(), false); })
Z80_OPCODE(3C, true, "SRL H", { SR_reg(&m_registers.H(), false); })
Z80_OPCODE(3D, true, "SRL L", { SR_reg(&m_registers.L(), false); })
Z80_OPCODE(3E, true, "SRL (HL)", { SRL_addrreg(m_registers.HL); })
Z80_OPCODE(3F, true, "SRL A", { SR_reg(&m_registers.A(), false); })
Z80_OPCODE(40, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(41, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(42, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(43, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(44, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(45, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(46, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(47, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(48, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(49, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(4A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(4B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(4C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(4D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(4E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(4F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(50, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(51, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(52, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(53, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(54, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(55, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(56, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(57, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(58, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(59, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(5A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(5B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(5C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(5D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(5E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(5F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(60, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(61, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(62, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(63, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(64, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(65, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(66, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(67, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(68, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(69, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(6A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(6B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(6C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(6D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(6E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(6F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(70, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(71, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(72, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(73, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(74, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(75, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(76, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(77, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(78, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(79, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(7A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(7B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(7C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(7D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(7E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(7F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(80, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(81, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(82, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(83, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(84, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(85, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(86, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(87, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(88, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(89, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(90, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(91, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(92, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(93, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(94, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(95, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(96, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(97, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(98, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(99, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(AA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(AB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(AC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(AD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(AE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(AF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(BA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(BB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(BC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(BD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(BE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(BF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(ED, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
