//------------------------------------------------------------------------------
// *** DO NOT INCLUDE DIRECTLY ***
//
// These macros generate code and populate several tables related to opcodes automatically.
//------------------------------------------------------------------------------

Z80_OPCODE(00, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(01, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(02, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(03, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(04, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(05, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(06, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(07, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(08, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(09, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(0A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(0B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(0C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(0D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(0E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(0F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(10, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(11, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(12, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(13, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(14, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(15, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(16, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(17, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(18, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(19, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(1A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(1B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(1C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(1D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(1E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(1F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(20, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(21, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(22, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(23, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(24, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(25, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(26, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(27, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(28, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(29, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(2A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(2B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(2C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(2D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(2E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(2F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(30, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(31, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(32, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(33, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(34, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(35, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(36, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(37, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(38, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(39, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(3A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(3B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(3C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(3D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(3E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(3F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(40, true, "IN B, (C)", { IN_value_address(&m_registers.B(), m_registers.BC); })
Z80_OPCODE(41, true, "OUT (C), B", { OUT_address_value(m_registers.BC, m_registers.B()); })
Z80_OPCODE(42, true, "SBC HL, BC", { SBC16_reg(m_registers.BC); })
Z80_OPCODE(43, true, "LD (%nn), BC", { LD16_addrnn_reg(m_registers.BC); })
Z80_OPCODE(44, true, "NEG", { NEG(); })
Z80_OPCODE(45, true, "RETN", { RETN(); })
Z80_OPCODE(46, true, "IM 0", { IM(0); })
Z80_OPCODE(47, true, "LD I, A", { LD8_reg_reg(&m_registers.I(), m_registers.A()); })
Z80_OPCODE(48, true, "IN C, (C)", { IN_value_address(&m_registers.C(), m_registers.BC); })
Z80_OPCODE(49, true, "OUT (C), C", { OUT_address_value(m_registers.BC, m_registers.C()); })
Z80_OPCODE(4A, true, "ADC HL, BC", { ADC16_reg_reg(&m_registers.HL, m_registers.BC); })
Z80_OPCODE(4B, true, "LD BC, (%nn)", { LD16_reg_addrnn(&m_registers.BC); })
Z80_OPCODE(4C, true, "NEG", { NEG(); })
Z80_OPCODE(4D, true, "RETI", { RETN(); /* Equivalent to RETN. */ })
Z80_OPCODE(4E, true, "IM 0", { IM(0); })
Z80_OPCODE(4F, true, "LD R, A", { LD8_reg_reg(&m_registers.R(), m_registers.A()); })
Z80_OPCODE(50, true, "IN D, (C)", { IN_value_address(&m_registers.D(), m_registers.BC); })
Z80_OPCODE(51, true, "OUT (C), D", { OUT_address_value(m_registers.BC, m_registers.D()); })
Z80_OPCODE(52, true, "SBC HL, DE", { SBC16_reg(m_registers.DE); })
Z80_OPCODE(53, true, "LD (%nn), DE", { LD16_addrnn_reg(m_registers.DE); })
Z80_OPCODE(54, true, "NEG", { NEG(); })
Z80_OPCODE(55, true, "RETN", { RETN(); })
Z80_OPCODE(56, true, "IM 1", { IM(1); })
Z80_OPCODE(57, true, "LD A, I", { LD8_reg_reg(&m_registers.A(), m_registers.I()); })
Z80_OPCODE(58, true, "IN E, (C)", { IN_value_address(&m_registers.E(), m_registers.BC); })
Z80_OPCODE(59, true, "OUT (C), E", { OUT_address_value(m_registers.BC, m_registers.E()); })
Z80_OPCODE(5A, true, "ADC HL, DE", { ADC16_reg_reg(&m_registers.HL, m_registers.DE); })
Z80_OPCODE(5B, true, "LD DE, (%nn)", { LD16_reg_addrnn(&m_registers.DE); })
Z80_OPCODE(5C, true, "NEG", { NEG(); })
Z80_OPCODE(5D, true, "RETN", { RETN(); })
Z80_OPCODE(5E, true, "IM 2", { IM(2); })
Z80_OPCODE(5F, true, "LD A, R", { LD8_reg_reg(&m_registers.A(), m_registers.R()); })
Z80_OPCODE(60, true, "IN H, (C)", { IN_value_address(&m_registers.H(), m_registers.BC); })
Z80_OPCODE(61, true, "OUT (C), H", { OUT_address_value(m_registers.BC, m_registers.H()); })
Z80_OPCODE(62, true, "SBC HL, HL", { SBC16_reg(m_registers.HL); })
Z80_OPCODE(63, true, "LD (%nn), HL", { LD16_addrnn_reg(m_registers.HL); })
Z80_OPCODE(64, true, "NEG", { NEG(); })
Z80_OPCODE(65, true, "RETN", { RETN(); })
Z80_OPCODE(66, true, "IM 0", { IM(0); })
Z80_OPCODE(67, true, "RRD", { RRD(); })
Z80_OPCODE(68, true, "IN L, (C)", { IN_value_address(&m_registers.L(), m_registers.BC); })
Z80_OPCODE(69, true, "OUT (C), L", { OUT_address_value(m_registers.BC, m_registers.L()); })
Z80_OPCODE(6A, true, "ADC HL, HL", { ADC16_reg_reg(&m_registers.HL, m_registers.HL); })
Z80_OPCODE(6B, true, "LD HL, (%nn)", { LD16_reg_addrnn(&m_registers.HL); })
Z80_OPCODE(6C, true, "NEG", { NEG(); })
Z80_OPCODE(6D, true, "RETN", { RETN(); })
Z80_OPCODE(6E, true, "IM 0", { IM(0); })
Z80_OPCODE(6F, true, "RLD", { RLD(); })
Z80_OPCODE(70, true, "IN (C)", { IN_value_address(NULL, m_registers.BC); })
Z80_OPCODE(71, true, "OUT (C), 0", { OUT_address_value(m_registers.BC, 0); })
Z80_OPCODE(72, true, "SBC HL, SP", { SBC16_reg(m_registers.SP); })
Z80_OPCODE(73, true, "LD (%nn), SP", { LD16_addrnn_reg(m_registers.SP); })
Z80_OPCODE(74, true, "NEG", { NEG(); })
Z80_OPCODE(75, true, "RETN", { RETN(); })
Z80_OPCODE(76, true, "IM 1", { IM(1); })
Z80_OPCODE(77, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(78, true, "IN A, (C)", { IN_value_address(&m_registers.A(), m_registers.BC); })
Z80_OPCODE(79, true, "OUT (C), A", { OUT_address_value(m_registers.BC, m_registers.A()); })
Z80_OPCODE(7A, true, "ADC HL, SP", { ADC16_reg_reg(&m_registers.HL, m_registers.SP); })
Z80_OPCODE(7B, true, "LD SP, (%nn)", { LD16_reg_addrnn(&m_registers.SP); })
Z80_OPCODE(7C, true, "NEG", { NEG(); })
Z80_OPCODE(7D, true, "RETN", { RETN(); })
Z80_OPCODE(7E, true, "IM 2", { IM(2); })
Z80_OPCODE(7F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(80, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(81, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(82, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(83, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(84, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(85, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(86, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(87, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(88, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(89, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(8F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(90, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(91, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(92, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(93, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(94, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(95, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(96, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(97, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(98, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(99, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9A, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9B, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9C, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9D, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9E, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(9F, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A0, true, "LDI", { LDI(); })
Z80_OPCODE(A1, true, "CPI", { CPI(); })
Z80_OPCODE(A2, true, "INI", { INI(); })
Z80_OPCODE(A3, true, "OUTI", { OUTI(); })
Z80_OPCODE(A4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(A8, true, "LDD", { LDD(); })
Z80_OPCODE(A9, true, "CPD", { CPD(); })
Z80_OPCODE(AA, true, "IND", { IND(); })
Z80_OPCODE(AB, true, "OUTD", { OUTD(); })
Z80_OPCODE(AC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(AD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(AE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(AF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B0, true, "LDIR", { LDIR(); })
Z80_OPCODE(B1, true, "CPIR", { CPIR(); })
Z80_OPCODE(B2, true, "INIR", { INIR(); })
Z80_OPCODE(B3, true, "OTIR", { OTIR(); })
Z80_OPCODE(B4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(B8, true, "LDDR", { LDDR(); })
Z80_OPCODE(B9, true, "CPDR", { CPDR(); })
Z80_OPCODE(BA, true, "INDR", { INDR(); })
Z80_OPCODE(BB, true, "OTDR", { OTDR(); })
Z80_OPCODE(BC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(BD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(BE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(BF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(C9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(CF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(D9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(DF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(E9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(ED, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(EF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F0, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F1, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F2, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F3, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F4, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F5, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F6, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F7, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F8, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(F9, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FA, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FB, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FC, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FD, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FE, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
Z80_OPCODE(FF, true, "<Invalid instruction>", { HandleInvalidInstruction(); })
