//-------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------

#include "stdafx.h"
#include "cpcVideoOutput.h"
#include "cpcMachine.h"
#include "cpcMemory.h"
#include "cpcMemoryBlock.h"
#include "cpcGateArray.h"


namespace CPC {

    CVideoOutput::CVideoOutput()
    {
        ResetVars();
    }

    void CVideoOutput::ResetVars()
    {
        m_machine = nullptr;
        m_horizontalOscillator.Initialize(IdealScanlinePeriod);
        m_verticalOscillator.Initialize(IdealFramePeriod);
    }

    void CVideoOutput::FreeVars()
    {
        //...
    }

    /*virtual*/ void CVideoOutput::Reset()
    {
        //...
    }

    unsigned CVideoOutput::GetBeamX() const
    {
        return m_horizontalOscillator.OffsetCounter();
    }

    unsigned CVideoOutput::GetBeamY() const
    {
        return m_verticalOscillator.OffsetCounter() / IdealScanlinePeriod;
    }

    void CVideoOutput::Run()
    {
        //
        // This runs on a 1 Mhz clock. Each pulse (i.e. each time CVideoOutput::Run is called), the beam advances 16 mode 2 pixels.
        //

        // Draw physical pixels.
        int beamX = GetBeamX();
        int beamY = GetBeamY();

        if ((((beamX + 1) * CGateArray::NUM_PHYSICAL_PIXELS_PER_CYCLE) <= BUFFER_WIDTH) &&    // Make sure we don't write outside of the buffer.
            (beamY < BUFFER_HEIGHT))
        {
            // The RGB values for the pixels are generated by the Gate Array.
            const unsigned* pixelRGBs = m_machine->GetGateArray()->GetGeneratedPhysicalPixels();
            // +- Calculate the pointer to the buffer that corresponds to the current beam position.
            static const unsigned BytesPerPixel = 4;
            const SBufferProperties& bufferProps = GetBufferProperties();
            unsigned char* destination = bufferProps.data + (beamY * bufferProps.nStride) + (beamX * CGateArray::NUM_PHYSICAL_PIXELS_PER_CYCLE * BytesPerPixel);
            KMASSERT(GetBufferProperties().eFormat == PIXELFORMAT_B8G8R8A8);
            memcpy(destination, pixelRGBs, CGateArray::NUM_PHYSICAL_PIXELS_PER_CYCLE * BytesPerPixel);
        }

        // Horizontal and vertical oscillators.
        m_horizontalOscillator.Tick();
        if (m_verticalOscillator.Tick())
        {
            // Let the client know that the monitor just completed a frame.
            OnBufferComplete();
        }
    }

    void CVideoOutput::OnGateArrayHSyncBegin()
    {
    }

    void CVideoOutput::OnGateArrayHSyncEnd()
    {
        m_horizontalOscillator.OnGateArraySync();
    }

    void CVideoOutput::OnGateArrayVSyncBegin()
    {
    }

    void CVideoOutput::OnGateArrayVSyncEnd()
    {
        m_verticalOscillator.OnGateArraySync();
    }

    void CVideoOutput::Oscillator::Initialize(int _idealPeriod)
    {
        period = _idealPeriod;
        counter = 0;
        gateArrayCounter = 0;
        offset = 0;
    }

    bool CVideoOutput::Oscillator::Tick()
    {
        counter++;
        gateArrayCounter++;

        if (counter >= period)
        {
            counter = 0;
            // Offset our counter to be in sync with the CRTC (H or V) SYNC signal.
            // TODO: Do this gradually to give it the analog feel that CRT monitors had.
            //////int offsetDiff = gateArrayCounter - offset;
            //////offset += min(offsetDiff, 64 * 5);
            // For now, the sync happens immediately.
            offset = gateArrayCounter;
            return true;
        }
        else
        {
            return false;
        }
    }

    void CVideoOutput::Oscillator::OnGateArraySync()
    {
        period = gateArrayCounter;
        gateArrayCounter = 0;
    }

    int CVideoOutput::Oscillator::OffsetCounter() const
    {
        return (counter + offset) % period;
    }

} //namespace CPC
