//-------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------

#include "stdafx.h"
#include "cpcVideoOutput.h"
#include "cpcMachine.h"
#include "cpcMemory.h"
#include "cpcMemoryBlock.h"
#include "cpcGateArray.h"


namespace CPC {

    CVideoOutput::CVideoOutput(CMachine *pMachine) : inherited(pMachine)
    {
        ResetVars();
    }

    void CVideoOutput::ResetVars()
    {
        m_HSyncActive = false;
        m_VSyncActive = false;
        m_beamX = 0;
        m_beamY = 0;
        m_frameCount = 0;
    }

    void CVideoOutput::FreeVars()
    {
        //...
    }

    /*virtual*/ void CVideoOutput::Reset()
    {
        //...
    }

    void CVideoOutput::Run()
    {
        if (!m_HSyncActive && !m_VSyncActive &&   // The beam is turned on only when both HSYNC and VSYNC are inactive.
            (m_beamY < BUFFER_HEIGHT))
        {
            // Draw physical pixels.
            // The RGB values for the pixels are generated by the Gate Array.
            const unsigned* pixelRGBs = m_pMachine->GetGateArray()->GetGeneratedPhysicalPixels();
            // +- Calculate the pointer to the buffer that corresponds to the current beam position.
            static const unsigned BytesPerPixel = 4;
            const SBufferProperties& bufferProps = GetBufferProperties();
            unsigned bytesPerRow = (bufferProps.nWidth * BytesPerPixel) + bufferProps.nStride;
            unsigned* destination = (unsigned*) (GetBuffer() + (m_beamY * bytesPerRow) + (m_beamX * BytesPerPixel));

            KMASSERT(GetBufferProperties().eFormat == PIXELFORMAT_B8G8R8X8);
            if ((m_beamX + CGateArray::NUM_PHYSICAL_PIXELS_PER_CYCLE) <= BUFFER_WIDTH)     // Make sure we don't write outside of the buffer. TODO: write as many pixels as possible.
            {
                memcpy(destination, pixelRGBs, CGateArray::NUM_PHYSICAL_PIXELS_PER_CYCLE * BytesPerPixel);
            }

            // Advance the beam horizontally.
            m_beamX += CGateArray::NUM_PHYSICAL_PIXELS_PER_CYCLE;
        }
    }

    void CVideoOutput::OnHSyncBegin()
    {
        m_HSyncActive = true;
        m_beamX = 0;
        m_beamY++;
    }

    void CVideoOutput::OnHSyncEnd()
    {
        m_HSyncActive = false;
    }

    void CVideoOutput::OnVSyncBegin()
    {
        m_VSyncActive = true;
        m_beamX = 0;
        m_beamY = 0;
        m_frameCount++;

        // Let client know.
        OnBufferComplete();
    }

    void CVideoOutput::OnVSyncEnd()
    {
        m_VSyncActive = false;
    }

} //namespace CPC
