//-------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------

#include "stdafx.h"
#include "cpcVideoOutput.h"
#include "cpcMachine.h"
#include "cpcMemory.h"
#include "cpcMemoryBlock.h"
#include "cpcGateArray.h"


// Final
// Memory     CRTC
// Address    Address
// -------    -------
// A15        MA13
// A14        MA12
// A13        RA2
// A12        RA1
// A11        RA0
// A10        MA9
// A9         MA8
// A8         MA7
// A7         MA6
// A6         MA5
// A5         MA4
// A4         MA3
// A3         MA2
// A2         MA1
// A1         MA0
// A0         CCLK
#define CONVERT_ADDRESS_CRTC_TO_MEMORY(_MA, _RA) \
  ( (((_MA) & 0x3000) <<  2) | \
    (((_RA) & 0x0007) << 11) | \
    (((_MA) & 0x03FF) <<  1) )


namespace CPC {

    CVideoOutput::CVideoOutput(CMachine *pMachine) : inherited(pMachine)
    {
        ResetVars();
    }

    void CVideoOutput::ResetVars()
    {
        m_HSyncActive = false;
        m_VSyncActive = false;
        m_beamX = 0;
        m_beamY = 0;
        m_frameCount = 0;
    }

    void CVideoOutput::FreeVars()
    {
        //...
    }

    /*virtual*/ void CVideoOutput::Reset()
    {
        //...
    }

    void CVideoOutput::Run()
    {
        if (!m_HSyncActive && !m_VSyncActive &&   // The beam is turned on only when both HSYNC and VSYNC are inactive.
            (m_beamY < BUFFER_HEIGHT))
        {
            // Draw physical pixels.
            // The RGB values for the pixels are generated by the Gate Array.
            const unsigned* pixelRGBs = m_pMachine->GetGateArray()->GetGeneratedPhysicalPixels();
            // +- Calculate the pointer to the buffer that corresponds to the current beam position.
            static const unsigned BytesPerPixel = 4;
            const SBufferProperties& bufferProps = GetBufferProperties();
            unsigned bytesPerRow = (bufferProps.nWidth * BytesPerPixel) + bufferProps.nStride;
            unsigned* destination = (unsigned*) (GetBuffer() + (m_beamY * bytesPerRow) + (m_beamX * BytesPerPixel));

            KMASSERT(GetBufferProperties().eFormat == PIXELFORMAT_B8G8R8X8);
            if ((m_beamX + CGateArray::NUM_PHYSICAL_PIXELS_PER_CYCLE) <= BUFFER_WIDTH)     // Make sure we don't write outside of the buffer. TODO: write as many pixels as possible.
            {
                memcpy(destination, pixelRGBs, CGateArray::NUM_PHYSICAL_PIXELS_PER_CYCLE * BytesPerPixel);
            }

            // Advance the beam horizontally.
            m_beamX += CGateArray::NUM_PHYSICAL_PIXELS_PER_CYCLE;
        }
    }

    void CVideoOutput::OnHSyncBegin()
    {
        m_HSyncActive = true;
        m_beamX = 0;
        m_beamY++;
    }

    void CVideoOutput::OnHSyncEnd()
    {
        m_HSyncActive = false;
    }

    void CVideoOutput::OnVSyncBegin()
    {
        m_VSyncActive = true;
        m_beamX = 0;
        m_beamY = 0;
        m_frameCount++;

        // Let client know.
        OnBufferComplete();
    }

    void CVideoOutput::OnVSyncEnd()
    {
        m_VSyncActive = false;
    }

} //namespace CPC
